package io.github.liveyum.iotools;

import android.app.AlertDialog;
import android.content.Context;
import android.text.InputType;
import android.view.View;
import android.widget.*;
import org.json.*;
import java.io.File;
import java.util.*;

/** Touch editors for structured parameters, with an explicit raw JSON escape hatch. */
final class FormDialogs {
    private final NativeUi ui;
    FormDialogs(Context context){ui=new NativeUi(context);}
    private LinearLayout page(){LinearLayout p=ui.column();p.setPadding(ui.dp(20),ui.dp(8),ui.dp(20),ui.dp(16));return p;}
    private Object parse(EditText input,Object fallback)throws JSONException{return input.getText().toString().trim().isEmpty()?fallback:ExactJson.parse(input.getText().toString());}
    private void fail(Exception e){new AlertDialog.Builder(ui.context).setTitle("参数格式错误").setMessage(e.getMessage()).setPositiveButton("关闭",null).show();}
    boolean supports(String key){return Arrays.asList("headers","query","form_urlencoded","form_multipart","configs","labels","topics","node_ids","groups","arguments","crypto","request_transforms","response_transform").contains(key);}
    String title(String key){if(key.equals("arguments"))return "有序方法参数";if(key.equals("crypto"))return "加密配置";if(key.endsWith("transforms")||key.equals("response_transform"))return "转换步骤与顺序";if(key.equals("topics")||key.equals("node_ids")||key.equals("groups"))return "列表";return "键值表";}
    void edit(String key,EditText input){try{if(key.equals("arguments"))arguments(input);else if(key.equals("crypto"))codecs(input);else if(key.equals("request_transforms")||key.equals("response_transform"))transforms(input,key.equals("request_transforms"));else if(key.equals("topics")||key.equals("node_ids")||key.equals("groups"))list(input);else map(input,key);}catch(Exception error){fail(error);}}
    void attachment(EditText input){File[] files=ui.context.getFilesDir().listFiles(File::isFile);if(files==null||files.length==0){new AlertDialog.Builder(ui.context).setTitle("没有已导入附件").setMessage("请先从设置 → 导入证书 / 数据附件选择文件").setPositiveButton("知道了",null).show();return;}Arrays.sort(files,Comparator.comparing(File::getName));String[] names=new String[files.length];for(int i=0;i<files.length;i++)names[i]=files[i].getName();new AlertDialog.Builder(ui.context).setTitle("选择应用私有文件").setItems(names,(d,i)->input.setText(files[i].getAbsolutePath())).setNegativeButton("取消",null).show();}
    private void list(EditText target)throws JSONException{Object raw=parse(target,new JSONArray());if(!(raw instanceof JSONArray))throw new JSONException("列表参数需要 JSON 数组");JSONArray values=(JSONArray)raw;StringBuilder text=new StringBuilder();for(int i=0;i<values.length();i++){if(i>0)text.append('\n');text.append(values.optString(i));}LinearLayout page=page();page.addView(ui.text("每行一项，按当前顺序保留",13,NativeUi.MUTED));EditText input=ui.input("每行一项",text.toString(),true);page.addView(input);new AlertDialog.Builder(ui.context).setTitle("编辑列表").setView(ui.scroll(page)).setNegativeButton("取消",null).setPositiveButton("应用到草稿",(d,w)->{JSONArray result=new JSONArray();for(String line:input.getText().toString().split("\\r?\\n"))if(!line.trim().isEmpty())result.put(line.trim());target.setText(NativeUi.pretty(result));}).show();}
    private static final class Pair {EditText key,value;Spinner kind;LinearLayout view;}
    private void map(EditText target,String parameter)throws JSONException{Object raw=parse(target,new JSONObject());if(!(raw instanceof JSONObject))throw new JSONException("键值参数需要 JSON 对象");JSONObject values=(JSONObject)raw;LinearLayout page=page(),rows=ui.column();ArrayList<Pair> entries=new ArrayList<>();page.addView(ui.text("重复的键会按顺序保存为数组；值可选择文本或 JSON",13,NativeUi.MUTED));page.addView(rows);Iterator<String> keys=values.keys();while(keys.hasNext()){String key=keys.next();Object value=values.opt(key);if(value instanceof JSONArray){JSONArray list=(JSONArray)value;for(int i=0;i<list.length();i++)pair(rows,entries,key,list.opt(i));}else pair(rows,entries,key,value);}if(entries.isEmpty())pair(rows,entries,"","");page.addView(ui.button("＋ 添加一行",false,()->pair(rows,entries,"","")));AlertDialog dialog=new AlertDialog.Builder(ui.context).setTitle("编辑 "+parameter).setView(ui.scroll(page)).setNegativeButton("取消",null).setPositiveButton("应用到草稿",null).create();dialog.setOnShowListener(d->dialog.getButton(-1).setOnClickListener(v->{try{JSONObject result=new JSONObject();for(Pair entry:entries){String key=entry.key.getText().toString().trim();if(key.isEmpty())continue;String text=entry.value.getText().toString();Object value=entry.kind.getSelectedItemPosition()==0?text:ExactJson.parse(text);if(result.has(key)){Object previous=result.get(key);JSONArray list=previous instanceof JSONArray?(JSONArray)previous:new JSONArray().put(previous);list.put(value);result.put(key,list);}else result.put(key,value);}target.setText(NativeUi.pretty(result));dialog.dismiss();}catch(Exception error){fail(error);}}));dialog.show();}
    private void pair(LinearLayout parent,List<Pair> entries,String key,Object value){Pair pair=new Pair();pair.view=ui.card();pair.key=ui.input("名称",key,false);pair.value=ui.input("值",value instanceof String?(String)value:NativeUi.pretty(value),true);pair.kind=picker(pair.view,"值类型",new String[]{"文本","JSON"},value instanceof String?"文本":"JSON");pair.view.addView(ui.label("键"));pair.view.addView(pair.key);pair.view.addView(ui.label("值"));pair.view.addView(pair.value);if(key.toLowerCase(Locale.ROOT).matches(".*(authorization|cookie|password|token|secret|api.?key).*")){pair.value.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);pair.view.addView(ui.button("显示 / 隐藏敏感值",false,()->reveal(pair.value)));}pair.view.addView(ui.button("移除此行",false,()->{entries.remove(pair);parent.removeView(pair.view);}));entries.add(pair);parent.addView(pair.view);}
    private void reveal(EditText input){boolean hidden=input.getTransformationMethod() instanceof android.text.method.PasswordTransformationMethod;input.setTransformationMethod(hidden?null:android.text.method.PasswordTransformationMethod.getInstance());input.setSelection(input.length());}
    private Spinner picker(LinearLayout page,String label,String[] options,String current){page.addView(ui.label(label));Spinner s=new Spinner(ui.context);ArrayAdapter<String> adapter=new ArrayAdapter<>(ui.context,android.R.layout.simple_spinner_item,options);adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);s.setAdapter(adapter);int selected=Arrays.asList(options).indexOf(current);s.setSelection(Math.max(0,selected));page.addView(s,new LinearLayout.LayoutParams(-1,ui.dp(50)));return s;}
    private EditText field(LinearLayout page,String label,String hint,String value,boolean multi){page.addView(ui.label(label));EditText input=ui.input(hint,value,multi);page.addView(input);return input;}
    private void transforms(EditText target,boolean request)throws JSONException{Object raw=parse(target,new JSONArray());if(!(raw instanceof JSONArray))throw new JSONException("转换规则需要 JSON 数组");ArrayList<JSONObject> steps=new ArrayList<>();JSONArray initial=(JSONArray)raw;for(int i=0;i<initial.length();i++){JSONObject step=initial.optJSONObject(i);if(step==null)throw new JSONException("每一步必须为对象");steps.add(NativeUi.clone(step));}LinearLayout page=page(),list=ui.column();page.addView(ui.text("按从上到下的顺序执行。修改只应用到当前请求草稿",13,NativeUi.MUTED));page.addView(list);Runnable[] render={null};render[0]=()->{list.removeAllViews();for(int i=0;i<steps.size();i++){int index=i;JSONObject step=steps.get(i);LinearLayout card=ui.card();card.addView(ui.title((i+1)+". "+step.optString("type")+" · "+step.optString("crypto"),16));card.addView(ui.text(request?step.optString("target")+" "+step.optString("name"):step.optString("scope","fields")+" "+step.optString("paths"),13,NativeUi.MUTED));LinearLayout controls=ui.row();ui.weighted(controls,ui.button("编辑",false,()->stepEditor(step,request,changed->{steps.set(index,changed);render[0].run();})));ui.weighted(controls,ui.button("上移",false,()->{if(index>0){Collections.swap(steps,index,index-1);render[0].run();}}));ui.weighted(controls,ui.button("下移",false,()->{if(index+1<steps.size()){Collections.swap(steps,index,index+1);render[0].run();}}));ui.weighted(controls,ui.button("删除",false,()->{steps.remove(index);render[0].run();}));card.addView(controls);list.addView(card);}};render[0].run();page.addView(ui.button("＋ 添加步骤",false,()->stepEditor(new JSONObject(),request,step->{steps.add(step);render[0].run();})));new AlertDialog.Builder(ui.context).setTitle(request?"请求转换":"响应转换").setView(ui.scroll(page)).setNegativeButton("取消",null).setPositiveButton("应用到草稿",(d,w)->target.setText(NativeUi.pretty(new JSONArray(steps)))).show();}
    private void stepEditor(JSONObject original,boolean request,java.util.function.Consumer<JSONObject> save){LinearLayout page=page();Spinner type=picker(page,"转换类型",request?new String[]{"encode","decode","encrypt","decrypt"}:new String[]{"decode","decrypt","encode","encrypt","parse_json"},original.optString("type"));EditText crypto=field(page,"加密配置名称","crypto 中定义的名称",original.optString("crypto"),false);Spinner target=picker(page,request?"转换目标":"作用范围",request?new String[]{"body","header","query","json"}:new String[]{"fields","body"},original.optString(request?"target":"scope","fields"));EditText name=field(page,request?"目标名称 / JSONPath":"JSONPath（每行一条）",request?"header / query 名称或 $.field":"$.field",request?original.optString("name"):joinLines(original.optJSONArray("paths")),!request);CheckBox missing=new CheckBox(ui.context),nil=new CheckBox(ui.context),blank=new CheckBox(ui.context);missing.setText("跳过缺失字段");missing.setChecked(original.optBoolean("skip_missing"));nil.setText("跳过 null");nil.setChecked(original.optBoolean("skip_null"));blank.setText("跳过空白");blank.setChecked(original.optBoolean("skip_blank"));if(!request){page.addView(missing);page.addView(nil);page.addView(blank);}new AlertDialog.Builder(ui.context).setTitle("编辑转换步骤").setView(ui.scroll(page)).setNegativeButton("取消",null).setPositiveButton("完成",(d,w)->{JSONObject step=NativeUi.clone(original);try{step.put("type",type.getSelectedItem().toString());String codec=crypto.getText().toString();if(codec.isEmpty())step.remove("crypto");else step.put("crypto",codec);String scope=target.getSelectedItem().toString();step.put(request?"target":"scope",scope);if(request){if(name.length()>0)step.put("name",name.getText().toString());else step.remove("name");}else if(scope.equals("body")){step.put("parse","json");step.remove("paths");step.remove("skip_missing");step.remove("skip_null");step.remove("skip_blank");}else{JSONArray paths=new JSONArray();for(String line:name.getText().toString().split("\\r?\\n"))if(!line.trim().isEmpty())paths.put(line.trim());step.put("paths",paths);step.put("skip_missing",missing.isChecked());step.put("skip_null",nil.isChecked());step.put("skip_blank",blank.isChecked());step.remove("parse");step.remove("text_encoding");}save.accept(step);}catch(JSONException error){fail(error);}}).show();}
    private String joinLines(JSONArray values){if(values==null)return "";StringBuilder out=new StringBuilder();for(int i=0;i<values.length();i++){if(i>0)out.append('\n');out.append(values.optString(i));}return out.toString();}
    void choice(EditText input,String key){String[] options;switch(key){case "word_order":options=new String[]{"ABCD","BADC","CDAB","DCBA"};break;case "payload_encoding":options=new String[]{"text","hex","base64"};break;case "security_mode":options=new String[]{"SignAndEncrypt","Sign","None"};break;case "security_policy":options=new String[]{"Basic256Sha256","Aes128_Sha256_RsaOaep","Aes256_Sha256_RsaPss","None"};break;case "sasl":options=new String[]{"plain","scram-sha-256","scram-sha-512"};break;case "offset":options=new String[]{"earliest","latest","most-recent"};break;case "auth":options=new String[]{"anonymous","username","certificate"};break;default:options=new String[]{"Boolean","SByte","Byte","Int16","UInt16","Int32","UInt32","Int64","UInt64","Float","Double","String","DateTime","Guid","NodeId","ByteString","LocalizedText","QualifiedName","UInt64[]","Int64[]","String[]","u16","i16","u32","i32","u64","i64","f32","f64","ascii","hex"};}new AlertDialog.Builder(ui.context).setTitle("选择 "+key).setItems(options,(d,index)->input.setText(options[index])).setNegativeButton("取消",null).show();}
    private void arguments(EditText target)throws JSONException{Object raw=parse(target,new JSONArray());if(!(raw instanceof JSONArray))throw new JSONException("arguments 需要有序数组");ArrayList<JSONObject> values=new ArrayList<>();JSONArray initial=(JSONArray)raw;for(int i=0;i<initial.length();i++){JSONObject argument=initial.optJSONObject(i);if(argument==null)throw new JSONException("参数必须包含 type 与 value");values.add(NativeUi.clone(argument));}LinearLayout page=page(),list=ui.column();page.addView(ui.text("顺序必须与方法签名一致。64 位整数以精确文本保留",13,NativeUi.MUTED));page.addView(list);Runnable[] refresh={null};refresh[0]=()->{list.removeAllViews();for(int i=0;i<values.size();i++){int index=i;JSONObject argument=values.get(i);LinearLayout row=ui.column();row.addView(ui.title((i+1)+" · "+argument.optString("type"),16));row.addView(ui.text(NativeUi.pretty(argument.opt("value")),13,NativeUi.MUTED));LinearLayout controls=ui.row();ui.weighted(controls,ui.button("编辑",false,()->argumentEditor(argument,result->{values.set(index,result);refresh[0].run();})));ui.weighted(controls,ui.button("上移",false,()->{if(index>0){Collections.swap(values,index,index-1);refresh[0].run();}}));ui.weighted(controls,ui.button("移除",false,()->{values.remove(index);refresh[0].run();}));row.addView(controls);ui.gap(row,12);list.addView(row);}};refresh[0].run();page.addView(ui.button("＋ 添加参数",false,()->argumentEditor(new JSONObject(),argument->{values.add(argument);refresh[0].run();})));new AlertDialog.Builder(ui.context).setTitle("方法参数").setView(ui.scroll(page)).setNegativeButton("取消",null).setPositiveButton("应用到草稿",(d,w)->target.setText(NativeUi.pretty(new JSONArray(values)))).show();}
    private void argumentEditor(JSONObject original,java.util.function.Consumer<JSONObject> done){LinearLayout page=page();EditText type=field(page,"OPC UA 类型","例如 UInt64 / String / Int32[]",original.optString("type","String"),false);page.addView(ui.button("选择类型",false,()->choice(type,"value_type")));Object originalValue=original.opt("value");EditText value=field(page,"参数值","标量输入文本；数组 / 结构输入 JSON",originalValue instanceof String?(String)originalValue:originalValue==null?"":NativeUi.pretty(originalValue),true);AlertDialog dialog=new AlertDialog.Builder(ui.context).setTitle("编辑方法参数").setView(ui.scroll(page)).setNegativeButton("取消",null).setPositiveButton("完成",null).create();dialog.setOnShowListener(d->dialog.getButton(-1).setOnClickListener(v->{try{String kind=type.getText().toString().trim(),text=value.getText().toString();Object parsed=text;if(kind.endsWith("[]")||kind.equals("LocalizedText")||kind.equals("QualifiedName"))parsed=ExactJson.parse(text);else if(kind.equals("Boolean")){if(!text.equals("true")&&!text.equals("false"))throw new JSONException("Boolean 使用 true 或 false");parsed=Boolean.valueOf(text);}done.accept(NativeUi.json("type",kind,"value",parsed));dialog.dismiss();}catch(Exception error){fail(error);}}));dialog.show();}
    private void codecs(EditText target)throws JSONException{Object raw=parse(target,new JSONObject());if(!(raw instanceof JSONObject))throw new JSONException("crypto 需要名称到配置的映射");JSONObject codecs=NativeUi.clone((JSONObject)raw);LinearLayout page=page(),list=ui.column();page.addView(ui.text("密钥与 IV 默认隐藏，仅在点按保存请求后写入配置",13,NativeUi.MUTED));page.addView(list);Runnable[] render={null};render[0]=()->{list.removeAllViews();Iterator<String> names=codecs.keys();while(names.hasNext()){String name=names.next();JSONObject config=NativeUi.object(codecs.opt(name));LinearLayout row=ui.row();ui.weighted(row,ui.button(name+" · "+config.optString("algorithm"),false,()->codecEditor(name,config,(newName,value)->{codecs.remove(name);try{codecs.put(newName,value);}catch(JSONException ignored){}render[0].run();})));row.addView(ui.button("移除",false,()->{codecs.remove(name);render[0].run();}));list.addView(row);}};render[0].run();page.addView(ui.button("＋ 添加加密配置",false,()->codecEditor("",new JSONObject(),(name,value)->{try{codecs.put(name,value);}catch(JSONException ignored){}render[0].run();})));new AlertDialog.Builder(ui.context).setTitle("加密配置").setView(ui.scroll(page)).setNegativeButton("取消",null).setPositiveButton("应用到草稿",(d,w)->target.setText(NativeUi.pretty(codecs))).show();}
    private interface CodecSave{void save(String name,JSONObject value);}
    private void codecEditor(String originalName,JSONObject original,CodecSave callback){LinearLayout page=page();EditText name=field(page,"配置名称","例如 my-aes",originalName,false);Spinner algorithm=picker(page,"算法",new String[]{"base64","base64url","aes-128-cbc","aes-192-cbc","aes-256-cbc","aes-128-ecb","aes-192-ecb","aes-256-ecb","none"},original.optString("algorithm"));JSONObject oldKey=NativeUi.object(original.opt("key")),oldIV=NativeUi.object(original.opt("iv"));EditText key=field(page,"密钥","AES 密钥",oldKey.optString("value"),false);key.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);Spinner keyEncoding=picker(page,"密钥编码",new String[]{"text","hex","base64"},oldKey.optString("encoding","text"));EditText iv=field(page,"IV","CBC 初始化向量",oldIV.optString("value"),false);iv.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);Spinner ivEncoding=picker(page,"IV 编码",new String[]{"text","hex","base64"},oldIV.optString("encoding","text"));page.addView(ui.button("显示 / 隐藏密钥材料",false,()->{reveal(key);reveal(iv);}));Spinner cipher=picker(page,"密文编码",new String[]{"base64","hex","base64url"},original.optString("ciphertext_encoding","base64"));new AlertDialog.Builder(ui.context).setTitle("编辑加密配置").setView(ui.scroll(page)).setNegativeButton("取消",null).setPositiveButton("完成",(d,w)->{String label=name.getText().toString().trim();if(label.isEmpty()){fail(new JSONException("配置名称不能为空"));return;}JSONObject result=NativeUi.clone(original);try{result.put("algorithm",algorithm.getSelectedItem().toString());if(key.length()>0)result.put("key",NativeUi.json("value",key.getText().toString(),"encoding",keyEncoding.getSelectedItem().toString()));else result.remove("key");if(iv.length()>0)result.put("iv",NativeUi.json("value",iv.getText().toString(),"encoding",ivEncoding.getSelectedItem().toString()));else result.remove("iv");result.put("ciphertext_encoding",cipher.getSelectedItem().toString());callback.save(label,result);}catch(JSONException error){fail(error);}}).show();}
}
