package io.github.liveyum.iotools;

import android.app.*;
import android.os.*;
import android.content.*;
import android.content.res.Configuration;
import android.graphics.Color;
import android.net.Uri;
import android.text.*;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;

/** Native touch workspace for the shared Go protocol engine. */
public class MainActivity extends Activity implements ResultViews.Actions {
    private final Handler handler=new Handler(Looper.getMainLooper());
    private final ExecutorService worker=Executors.newSingleThreadExecutor();
    private final LinkedHashMap<String,JSONObject> drafts=new LinkedHashMap<>();
    private final ArrayList<JSONObject> events=new ArrayList<>();
    private final HashSet<String> interactions=new HashSet<>();
    private NativeUi ui;
    private LinearLayout root,content,bottom,requestList,resultList;
    private TextView statusView;
    private RequestEditor editor;
    private EditText yamlEditor;
    private JSONObject state=new JSONObject(),catalog=new JSONObject(),selected;
    private String source="",yamlDraft=null,search="",protocolFilter="all",resultFilter="all",topicFilter="",workspaceTab="form",selectedKey="";
    private int tab=0;
    private boolean active,ready,destroyed,polling,running,yamlDirty;
    private String runId="";
    private String status="正在准备本机协议引擎…";
    private File config;
    private static final int IMPORT=21,EXPORT=22,IMPORT_FILE=23,EXPORT_FILE=24,EXPORT_TEXT=25;
    private File exportSource;
    private String exportText;
    private final Runnable poll=new Runnable(){public void run(){if(!active||!ready||destroyed)return;if(!polling){polling=true;call(NativeUi.json("op","events"),data->{polling=false;acceptEvents(NativeUi.object(data));},error->{polling=false;setStatus(error,true);});}handler.postDelayed(this,running?250:650);}};

    @Override public void onCreate(Bundle saved){
        setTheme(themeIsDark()?R.style.AppTheme:R.style.AppThemeLight);super.onCreate(saved);applyTheme();ui=new NativeUi(this);config=new File(getFilesDir(),"iotools.yaml");
        if(saved!=null)restore(saved);buildShell();render();
        UsbSerialTransport.initialize(this,message->{if(!destroyed)setStatus(message,false);});
        worker.execute(()->{try{Object opened=unwrap(NativeRuntime.open(config.getAbsolutePath(),"1",getPreferences(0).getBoolean("readonly",false),getPreferences(0).getBoolean("history",false)));JSONObject c=NativeUi.object(unwrap(NativeRuntime.command(NativeUi.json("op","catalog").toString())));JSONObject s=NativeUi.object(unwrap(NativeRuntime.command(NativeUi.json("op","state").toString())));JSONObject document=NativeUi.object(unwrap(NativeRuntime.command(NativeUi.json("op","config.get").toString())));handler.post(()->{if(destroyed)return;catalog=c;state=s;source=document.optString("source");ready=true;running=s.optBoolean("running");runId=s.optString("run_id");if(selected==null&&!selectedKey.isEmpty())selected=findRequest(selectedKey);setStatus("本机引擎就绪 · 仅在点按执行后连接",false);render();if(active){NativeRuntime.resume();handler.removeCallbacks(poll);handler.post(poll);}});}catch(Throwable error){handler.post(()->{if(!destroyed){setStatus("引擎初始化失败："+message(error),true);render();}});}});
    }
    private void buildShell(){
        root=ui.column();root.setBackgroundColor(NativeUi.BG);root.setFitsSystemWindows(false);
        root.setOnApplyWindowInsetsListener((view,insets)->{view.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets;});
        LinearLayout top=ui.column();top.setPadding(ui.dp(22),ui.dp(16),ui.dp(22),ui.dp(9));LinearLayout brand=ui.row();TextView mark=ui.title("io",23);mark.setTextColor(Color.WHITE);mark.setGravity(Gravity.CENTER);mark.setBackground(ui.shape(NativeUi.ACCENT,12));brand.addView(mark,new LinearLayout.LayoutParams(ui.dp(42),ui.dp(42)));LinearLayout word=ui.column();word.setPadding(ui.dp(12),0,0,0);word.addView(ui.title("iotools",21));word.addView(ui.text("协议工具 · 原生工作台",11,NativeUi.MUTED));brand.addView(word,new LinearLayout.LayoutParams(0,-2,1));Button help=ui.button("帮助",false,this::help);brand.addView(help);top.addView(brand);statusView=ui.text(status,12,NativeUi.MUTED);statusView.setId(R.id.runtime_status);statusView.setPadding(0,ui.dp(10),0,0);statusView.setAccessibilityLiveRegion(View.ACCESSIBILITY_LIVE_REGION_POLITE);top.addView(statusView);root.addView(top);
        content=ui.column();root.addView(content,new LinearLayout.LayoutParams(-1,0,1));bottom=ui.row();bottom.setPadding(ui.dp(10),ui.dp(8),ui.dp(10),ui.dp(8));bottom.setBackgroundColor(NativeUi.CARD);root.addView(bottom,new LinearLayout.LayoutParams(-1,ui.dp(74)));setContentView(root);renderBottom();
    }
    private void renderBottom(){bottom.removeAllViews();String[] titles={"请求","工作台","历史","设置"};String[] icons={"▦","▤","◷","⚙"};int[] ids={R.id.nav_requests,R.id.nav_workspace,R.id.nav_history,R.id.nav_settings};for(int i=0;i<4;i++){final int target=i;TextView b=ui.text(icons[i]+"\n"+titles[i],13,tab==i?NativeUi.ACCENT:NativeUi.MUTED);b.setId(ids[i]);b.setGravity(Gravity.CENTER);b.setContentDescription(titles[i]);b.setBackground(ui.shape(tab==i?NativeUi.TINT:NativeUi.CARD,14));b.setOnClickListener(v->navigate(target));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-1,1);p.leftMargin=ui.dp(3);p.rightMargin=ui.dp(3);bottom.addView(b,p);}}
    private void navigate(int target){captureDraft();hideKeyboard();tab=target;render();}
    private LinearLayout page(){LinearLayout page=ui.column();page.setPadding(ui.dp(20),ui.dp(12),ui.dp(20),ui.dp(24));return page;}
    private void mount(LinearLayout page){content.addView(ui.scroll(page),new LinearLayout.LayoutParams(-1,-1));}
    private void render(){if(content==null)return;editor=null;yamlEditor=null;requestList=null;resultList=null;content.removeAllViews();renderBottom();if(!ready){LinearLayout page=page();page.addView(ui.title("准备工作台",28));ui.gap(page,14);page.addView(ui.text(status,15,NativeUi.MUTED));if(!status.contains("失败"))page.addView(new ProgressBar(this));mount(page);return;}switch(tab){case 0:renderRequests();break;case 1:renderWorkspace();break;case 2:renderHistory();break;default:renderSettings();}}
    private void heading(LinearLayout page,String title,String subtitle){page.addView(ui.title(title,28));TextView hint=ui.text(subtitle,13,NativeUi.MUTED);hint.setPadding(0,ui.dp(4),0,ui.dp(16));page.addView(hint);}

    private void renderRequests(){
        LinearLayout page=page();heading(page,"连接，从这里开始","收藏请求、切换环境，随时回到未完成的草稿");
        LinearLayout controls=ui.row();Button profile=ui.button("环境 · "+state.optString("profile","默认"),false,this::profiles);ui.weighted(controls,profile);Button add=ui.button("＋ 新建请求",true,this::newRequest);add.setId(R.id.new_request);ui.weighted(controls,add);page.addView(controls);ui.gap(page,14);
        EditText searchBox=ui.input("搜索名称、地址或操作",search,false);searchBox.setId(R.id.search_requests);searchBox.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void onTextChanged(CharSequence s,int start,int before,int count){search=s.toString();renderRequestCards();}public void afterTextChanged(Editable e){}});page.addView(searchBox);ui.gap(page,12);
        LinearLayout chips=ui.row();chips.addView(ui.chip("全部",protocolFilter.equals("all"),()->{protocolFilter="all";render();}));JSONArray protocols=catalog.optJSONArray("protocols");if(protocols!=null)for(int i=0;i<protocols.length();i++){JSONObject p=protocols.optJSONObject(i);if(p==null)continue;String id=p.optString("id");chips.addView(ui.chip(p.optString("name",id),protocolFilter.equals(id),()->{protocolFilter=id;render();}));}page.addView(ui.chips(chips));ui.gap(page,16);
        requestList=ui.column();requestList.setId(R.id.request_list);page.addView(requestList);renderRequestCards();mount(page);
    }
    private void renderRequestCards(){if(requestList==null)return;requestList.removeAllViews();JSONArray requests=state.optJSONArray("requests");int shown=0;if(requests!=null)for(int i=0;i<requests.length();i++){JSONObject request=requests.optJSONObject(i);if(request==null)continue;String protocol=request.optString("protocol");if(!protocolFilter.equals("all")&&!protocolFilter.equals(protocol))continue;String match=(request.optString("name")+" "+request.optString("id")+" "+request.optString("endpoint")+" "+request.optString("action")).toLowerCase(Locale.ROOT);if(!match.contains(search.toLowerCase(Locale.ROOT)))continue;shown++;LinearLayout card=ui.card();card.setContentDescription("请求 "+request.optString("name",request.optString("id")));LinearLayout head=ui.row();TextView label=ui.text(protocol.toUpperCase(Locale.ROOT),11,NativeUi.ACCENT);label.setPadding(ui.dp(10),ui.dp(5),ui.dp(10),ui.dp(5));label.setBackground(ui.shape(NativeUi.TINT,8));head.addView(label);TextView action=ui.text(request.optString("action"),12,NativeUi.MUTED);action.setPadding(ui.dp(10),0,0,0);head.addView(action,new LinearLayout.LayoutParams(0,-2,1));head.addView(ui.text("›",25,NativeUi.MUTED));card.addView(head);ui.gap(card,12);String name=request.optString("name");card.addView(ui.title(name.isEmpty()?request.optString("id"):name,19));TextView endpoint=ui.text(request.optString("endpoint"),13,NativeUi.MUTED);endpoint.setPadding(0,ui.dp(5),0,0);endpoint.setMaxLines(2);card.addView(endpoint);if(drafts.containsKey(request.optString("id"))){TextView draft=ui.text("● 未保存草稿",11,NativeUi.ACCENT);draft.setPadding(0,ui.dp(8),0,0);card.addView(draft);}card.setOnClickListener(v->selectRequest(request));requestList.addView(card);}
        if(shown==0){LinearLayout empty=ui.card();empty.addView(ui.title("没有找到请求",20));empty.addView(ui.text(search.isEmpty()?"新建一个请求，或从设置导入 YAML 配置":"试试不同的关键词或协议",14,NativeUi.MUTED));requestList.addView(empty);}
    }
    private JSONObject protocol(String id){JSONArray protocols=catalog.optJSONArray("protocols");if(protocols!=null)for(int i=0;i<protocols.length();i++){JSONObject p=protocols.optJSONObject(i);if(p!=null&&id.equals(p.optString("id")))return p;}return NativeUi.json("id",id,"name",id.toUpperCase(Locale.ROOT));}
    private JSONObject findRequest(String id){JSONArray requests=state.optJSONArray("requests");if(requests!=null)for(int i=0;i<requests.length();i++){JSONObject r=requests.optJSONObject(i);if(r!=null&&id.equals(r.optString("id")))return NativeUi.clone(r);}return null;}
    private void selectRequest(JSONObject request){captureDraft();selected=NativeUi.clone(request);selectedKey=selected.optString("id");workspaceTab="form";tab=1;hideKeyboard();render();}
    private void profiles(){JSONArray p=state.optJSONArray("profiles");if(p==null||p.length()==0){toast("配置中没有环境，可在 YAML 中添加 profiles");return;}String[] names=new String[p.length()];for(int i=0;i<p.length();i++)names[i]=p.optString(i);new AlertDialog.Builder(this).setTitle("切换环境").setItems(names,(dialog,index)->{captureDraft();call(NativeUi.json("op","profile.set","profile",names[index]),data->refreshState(()->{setStatus("已切换至 "+names[index]+" · 不自动执行",false);render();}));}).setNegativeButton("取消",null).show();}
    private void newRequest(){JSONArray protocols=catalog.optJSONArray("protocols");if(protocols==null)return;String[] names=new String[protocols.length()];for(int i=0;i<names.length;i++)names[i]=protocols.optJSONObject(i).optString("name");new AlertDialog.Builder(this).setTitle("选择协议").setItems(names,(d,index)->chooseAction(protocols.optJSONObject(index))).setNegativeButton("取消",null).show();}
    private void chooseAction(JSONObject protocol){JSONArray actions=protocol.optJSONArray("actions");if(actions==null)return;String[] names=new String[actions.length()];for(int i=0;i<names.length;i++){JSONObject a=actions.optJSONObject(i);names[i]=a.optString("name",a.optString("id"))+" · "+a.optString("id")+(a.optBoolean("mutates")?"  [写入]":"");}new AlertDialog.Builder(this).setTitle(protocol.optString("name")+" · 新建操作").setItems(names,(d,index)->{JSONObject action=actions.optJSONObject(index);String p=protocol.optString("id");String endpoint=p.equals("http")?"https://":p.equals("mqtt")?"mqtt://":p.equals("opcua")?"opc.tcp://":p.equals("modbus")?"tcp://":"";JSONObject request=NativeUi.json("id",p+"-"+System.currentTimeMillis(),"name",action.optString("name",action.optString("id")),"protocol",p,"action",action.optString("id"),"endpoint",endpoint,"timeout","15s","params",NativeUi.object(action.opt("defaults")));selectRequest(request);}).setNegativeButton("返回",(d,w)->newRequest()).show();}

    private void renderWorkspace(){
        LinearLayout page=page();heading(page,"工作台",selected==null?"选择请求，或编辑整份 YAML 配置":selected.optString("name",selected.optString("id")));
        LinearLayout tabs=ui.row();String[] keys={"form","yaml","results","tools"},labels={"表单","YAML","结果","工具"};for(int i=0;i<keys.length;i++){String key=keys[i];tabs.addView(ui.chip(labels[i],workspaceTab.equals(key),()->{captureDraft();hideKeyboard();workspaceTab=key;render();}));}page.addView(ui.chips(tabs));ui.gap(page,14);
        if(workspaceTab.equals("yaml"))renderYaml(page);else if(workspaceTab.equals("results"))renderResults(page);else if(workspaceTab.equals("tools"))renderTools(page);else if(selected==null){LinearLayout c=ui.card();c.addView(ui.title("还没有选中请求",20));c.addView(ui.text("从请求列表打开，或新建任意协议操作",14,NativeUi.MUTED));ui.gap(c,16);c.addView(ui.button("＋ 新建请求",true,this::newRequest));page.addView(c);}else{
            editor=new RequestEditor(this,selected,protocol(selected.optString("protocol")),drafts.get(selectedKey));page.addView(editor.view);
            LinearLayout bar=ui.row();Button run=ui.button("执行",true,()->execute(false));run.setId(R.id.run_request);ui.weighted(bar,run);ui.weighted(bar,ui.button("预览",false,()->execute(true)));Button save=ui.button("保存请求",false,this::saveRequest);save.setId(R.id.save_request);ui.weighted(bar,save);page.addView(bar);ui.gap(page,10);page.addView(ui.text("修改先保留为草稿；保存后写入本机配置",12,NativeUi.MUTED));if(running){ui.gap(page,10);Button cancel=ui.button("取消当前任务",false,this::cancelRun);cancel.setId(R.id.cancel_request);page.addView(cancel);}
        }mount(page);
    }
    private void renderYaml(LinearLayout page){LinearLayout card=ui.card();card.addView(ui.title("请求配置 YAML",19));card.addView(ui.text("中文、注释与格式原样保留。保存时校验并原子写入",12,NativeUi.MUTED));ui.gap(card,12);yamlEditor=ui.input("version: 1",yamlDraft==null?source:yamlDraft,true);yamlEditor.setId(R.id.yaml_editor);yamlEditor.setTypeface(android.graphics.Typeface.MONOSPACE);yamlEditor.setTextSize(13);yamlEditor.setMinLines(16);yamlEditor.setHorizontallyScrolling(false);yamlEditor.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void onTextChanged(CharSequence s,int st,int b,int c){yamlDirty=true;}public void afterTextChanged(Editable e){}});card.addView(yamlEditor);page.addView(card);LinearLayout row=ui.row();Button save=ui.button("保存 YAML",true,this::saveYaml);save.setId(R.id.save_yaml);ui.weighted(row,save);ui.weighted(row,ui.button("导出已保存配置",false,()->exportConfig()));page.addView(row);}
    private void captureDraft(){if(editor!=null&&selected!=null)drafts.put(selectedKey,editor.draft());if(yamlEditor!=null)yamlDraft=yamlEditor.getText().toString();}
    private JSONObject currentRequest()throws JSONException{if(editor!=null)return editor.request();if(selected==null)throw new JSONException("请先选择请求");RequestEditor temporary=new RequestEditor(this,selected,protocol(selected.optString("protocol")),drafts.get(selectedKey));return temporary.request();}
    private void saveRequest(){try{JSONObject request=currentRequest();captureDraft();call(NativeUi.json("op","request.save","request",request,"original_id",findRequest(selectedKey)!=null?selectedKey:""),data->{drafts.remove(selectedKey);selected=request;selectedKey=request.optString("id");refreshState(()->refreshSource(()->{setStatus("请求已保存",false);render();}));});}catch(Exception error){error(message(error));}}
    private void saveYaml(){captureDraft();String value=yamlDraft==null?source:yamlDraft;Runnable save=()->call(NativeUi.json("op","config.save","source",value),data->{source=value;yamlDraft=value;yamlDirty=false;drafts.clear();refreshState(()->{if(selected!=null)selected=findRequest(selectedKey);setStatus("配置已保存",false);render();});});if(!drafts.isEmpty())confirm("保存整份 YAML","这会替换已保存配置，并清除表单中未保存的草稿。请确认 YAML 包含要保留的修改。","保存并替换",save);else save.run();}
    private void execute(boolean previewOnly){try{JSONObject request=currentRequest();captureDraft();hideKeyboard();setStatus("正在校验请求…",false);call(NativeUi.json("op","preview","request",request),data->{JSONObject preview=NativeUi.object(data);if(previewOnly){showPreview(preview,request);return;}confirmRun(preview,request);});}catch(Exception error){error(message(error));}}
    private void showPreview(JSONObject preview,JSONObject request){LinearLayout content=ui.column();content.setPadding(ui.dp(20),ui.dp(4),ui.dp(20),ui.dp(12));content.addView(ui.text(preview.optString("summary"),15,NativeUi.INK));content.addView(ui.selectable(NativeUi.pretty(preview.opt("request"))));if(preview.has("warnings"))content.addView(ui.text(NativeUi.pretty(preview.opt("warnings")),13,NativeUi.DANGER));new AlertDialog.Builder(this).setTitle("执行预览 · 尚未连接").setView(ui.scroll(content)).setNegativeButton("关闭",null).setPositiveButton("继续执行",(d,w)->confirmRun(preview,request)).show();}
    private void confirmRun(JSONObject preview,JSONObject request){if(preview.optBoolean("confirmation_required")||preview.optBoolean("mutates")){String text=preview.optString("summary")+"\n\n目标："+NativeUi.object(preview.opt("request")).optString("endpoint",request.optString("endpoint"))+"\n操作："+request.optString("action")+"\n\n"+NativeUi.pretty(NativeUi.object(preview.opt("request")).opt("params"));confirm("确认执行写入操作",text,"确认执行",()->startRun(preview,request,true));}else startRun(preview,request,false);}
    private void startRun(JSONObject preview,JSONObject request,boolean confirmed){call(NativeUi.json("op","run","token",preview.optString("token"),"confirmed",confirmed),data->{JSONObject response=NativeUi.object(data);runId=response.optString("run_id");running=true;events.clear();interactions.clear();topicFilter="";resultFilter="all";workspaceTab="results";tab=1;setStatus("正在执行 "+request.optString("action")+" · 可随时取消",false);render();});}
    private void cancelRun(){call(NativeUi.json("op","cancel"),data->{running=false;setStatus("已请求取消 · 草稿保留",false);if(tab==1&&workspaceTab.equals("results")){captureDraft();render();}});}
    private void acceptEvents(JSONObject result){boolean previous=running;running=result.optBoolean("running");runId=result.optString("run_id",runId);JSONArray batch=result.optJSONArray("events");boolean changed=false;if(batch!=null)for(int i=0;i<batch.length();i++){JSONObject event=batch.optJSONObject(i);if(event==null)continue;if(event.optString("kind").equals("interaction")){showInteraction(NativeUi.object(event.opt("data")));continue;}events.add(event);while(events.size()>500)events.remove(0);changed=true;}int dropped=result.optInt("dropped");if(dropped>0)setStatus("引擎已丢弃 "+dropped+" 条过量事件，请缩小订阅范围",true);else if(previous&&!running)setStatus("任务已结束 · "+events.size()+" 条结果",false);if((changed||previous!=running)&&tab==1&&workspaceTab.equals("results"))updateResults();}
    private void renderResults(LinearLayout page){LinearLayout toolbar=ui.row();TextView progress=ui.text(running?"● 执行中":"本次结果",14,running?NativeUi.ACCENT:NativeUi.MUTED);toolbar.addView(progress,new LinearLayout.LayoutParams(0,-2,1));if(running){Button stop=ui.button("取消任务",false,this::cancelRun);stop.setId(R.id.cancel_request);toolbar.addView(stop);}else toolbar.addView(ui.button("导出结果",false,()->exportText("iotools-results.json",new JSONArray(events).toString())));page.addView(toolbar);ui.gap(page,12);
        LinearLayout filters=ui.row();String[] keys={"all","message","reference","registers"},names={"全部","消息 / 主题","节点","寄存器"};for(int i=0;i<keys.length;i++){String key=keys[i];filters.addView(ui.chip(names[i],resultFilter.equals(key),()->{resultFilter=key;render();}));}page.addView(ui.chips(filters));ui.gap(page,12);
        resultList=ui.column();resultList.setId(R.id.result_list);page.addView(resultList);updateResults();
    }
    private void updateResults(){if(resultList==null)return;resultList.removeAllViews();if(events.isEmpty()){LinearLayout empty=ui.card();empty.addView(ui.title(running?"等待协议响应":"暂无执行结果",20));empty.addView(ui.text(running?"真实响应会实时显示在这里":"在表单中检查参数，然后点按执行",14,NativeUi.MUTED));if(running)empty.addView(new ProgressBar(this));resultList.addView(empty);return;}ResultViews renderer=new ResultViews(this,this);if(resultFilter.equals("message"))topicTree(resultList);int shown=0;for(int i=events.size()-1;i>=0;i--){JSONObject event=events.get(i);String kind=event.optString("kind");if(!resultFilter.equals("all")){if(resultFilter.equals("message")){if(!kind.equals("message")&&!kind.equals("record")&&!kind.equals("topics"))continue;}else if(!kind.equals(resultFilter))continue;}if(!topicFilter.isEmpty()&&!NativeUi.object(event.opt("data")).optString("topic").startsWith(topicFilter))continue;if(shown++>=120)break;resultList.addView(renderer.event(event));}if(shown==0)resultList.addView(ui.text("本次执行没有此类数据",14,NativeUi.MUTED));if(shown>120)resultList.addView(ui.text("显示最近 120 条；导出可查看已保留的全部事件",12,NativeUi.MUTED));}
    private void topicTree(LinearLayout parent){TreeMap<String,Integer> paths=new TreeMap<>();for(JSONObject event:events){String kind=event.optString("kind");if(!kind.equals("message")&&!kind.equals("record"))continue;String topic=NativeUi.object(event.opt("data")).optString("topic");if(topic.isEmpty())continue;String path="";for(String part:topic.split("/")){path+=(path.isEmpty()?"":"/")+part;paths.put(path,paths.getOrDefault(path,0)+1);}}if(paths.isEmpty())return;LinearLayout tree=ui.card();tree.addView(ui.title("主题导航",18));tree.addView(ui.button(topicFilter.isEmpty()?"全部消息":"清除筛选 · "+topicFilter,false,()->{topicFilter="";updateResults();}));int count=0;for(Map.Entry<String,Integer> path:paths.entrySet()){if(count++>=80)break;String key=path.getKey();int depth=key.split("/").length-1;Button b=ui.button("  ".repeat(Math.min(depth,5))+key.substring(key.lastIndexOf('/')+1)+"  ·  "+path.getValue(),false,()->{topicFilter=key;updateResults();});b.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);tree.addView(b);}parent.addView(tree);}
    @Override public void prepare(String action,String key,Object value){if(selected==null){error("请先选中来源请求");return;}captureDraft();try{JSONObject request=currentRequest();request.put("action",action);JSONObject params=NativeUi.object(request.opt("params"));params.put(key,value);if(key.equals("topic"))params.remove("topics");if(key.equals("node_id"))params.remove("node_ids");request.put("params",params);request.put("id",request.optString("protocol")+"-"+action+"-"+System.currentTimeMillis());request.put("name",action+" · "+String.valueOf(value));selected=request;selectedKey=request.optString("id");workspaceTab="form";tab=1;setStatus("已准备草稿 · 检查参数后点按执行",false);render();}catch(Exception error){error(message(error));}}

    private void showInteraction(JSONObject data){String id=data.optString("interaction_id");if(id.isEmpty()||!interactions.add(id))return;String type=data.optString("type"),title=data.optString("title","执行需要确认");AlertDialog.Builder dialog=new AlertDialog.Builder(this).setTitle(title).setNegativeButton("取消",(d,w)->respond(id,false,""));if(type.equals("select")){JSONArray options=NativeUi.array(data.opt("options"));String[] values=new String[options.length()];for(int i=0;i<values.length;i++)values[i]=options.optString(i);dialog.setItems(values,(d,w)->respond(id,true,values[w]));}else if(type.equals("prompt")){EditText input=ui.input(title,data.optString("default"),false);if(data.optBoolean("sensitive"))input.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);dialog.setView(input).setPositiveButton("继续",(d,w)->respond(id,true,input.getText().toString()));}else{dialog.setMessage(data.has("request")?NativeUi.pretty(data.opt("request")):"请确认此操作后继续").setPositiveButton("确认",(d,w)->respond(id,true,""));}dialog.setOnCancelListener(d->respond(id,false,""));dialog.show();}
    private void respond(String id,boolean confirmed,String value){call(NativeUi.json("op","respond","interaction_id",id,"confirmed",confirmed,"value",value),ignored->{});}

    private void renderHistory(){
        LinearLayout page=page();heading(page,"历史与活动","本次执行保留在内存；HTTP 历史需明确启用");
        LinearLayout shortcuts=ui.row();ui.weighted(shortcuts,ui.button("本次结果 · "+events.size(),false,()->{workspaceTab="results";navigate(1);}));ui.weighted(shortcuts,ui.button("SQL 查询",false,this::historySQL));page.addView(shortcuts);ui.gap(page,14);
        LinearLayout list=ui.column();list.addView(ui.text("正在读取本机历史…",14,NativeUi.MUTED));page.addView(list);mount(page);
        call(NativeUi.json("op","history.list"),data->{if(tab!=2)return;list.removeAllViews();JSONArray rows=NativeUi.array(data);if(rows.length()==0){LinearLayout empty=ui.card();empty.addView(ui.title("没有已保存的 HTTP 历史",19));empty.addView(ui.text("可在设置中启用。响应内容可能包含敏感信息，默认不写入磁盘",14,NativeUi.MUTED));list.addView(empty);return;}for(int i=0;i<rows.length();i++){JSONObject entry=rows.optJSONObject(i);if(entry==null)continue;LinearLayout card=ui.card();card.addView(ui.title(entry.optString("method")+"  "+entry.optString("recipe"),18));ui.pair(card,"状态 / 环境",entry.optString("status")+" / "+entry.optString("profile"));ui.pair(card,"时间",entry.optString("time"));card.setOnClickListener(v->historyDetail(entry.optLong("id")));list.addView(card);}},error->{list.removeAllViews();list.addView(ui.text(error,14,NativeUi.DANGER));});
    }
    private void historyDetail(long id){call(NativeUi.json("op","history.get","history_id",id),data->{JSONObject entry=NativeUi.object(data);LinearLayout c=page();c.addView(ui.title(entry.optString("method")+" · "+entry.optString("recipe"),18));ui.pair(c,"状态",entry.optString("status"));ui.pair(c,"时间",entry.optString("time"));new ResultViews(this,this).details(c,"响应头",entry.opt("headers"));String body=decodeBase64(entry.optString("body"));c.addView(ui.label("原始响应"));c.addView(ui.selectable(body));String transformed=entry.optString("transformed");if(!transformed.isEmpty())new ResultViews(this,this).details(c,"转换后响应",decodeBase64(transformed));new AlertDialog.Builder(this).setTitle("历史 #"+id).setView(ui.scroll(c)).setPositiveButton("关闭",null).setNeutralButton("导出",(d,w)->exportText("history-"+id+".json",NativeUi.pretty(entry))).setNegativeButton("删除",(d,w)->confirm("删除历史 #"+id,"只删除这一条本机 HTTP 历史，无法撤销。","删除",()->call(NativeUi.json("op","history.delete","ids",new JSONArray().put(id),"confirmed",true),ignored->{setStatus("历史已删除",false);render();}))).show();});}
    private String decodeBase64(String encoded){try{return new String(android.util.Base64.decode(encoded,android.util.Base64.DEFAULT),StandardCharsets.UTF_8);}catch(IllegalArgumentException error){return encoded;}}
    private void historySQL(){LinearLayout p=page();p.addView(ui.text("只读查询支持 SQL、.tables 与 .schema",13,NativeUi.MUTED));EditText sql=ui.input("SELECT id, recipe, status FROM http_history LIMIT 100","SELECT id, recipe, status FROM http_history ORDER BY id DESC LIMIT 100",true);sql.setTypeface(android.graphics.Typeface.MONOSPACE);p.addView(sql);new AlertDialog.Builder(this).setTitle("本机历史 SQL").setView(ui.scroll(p)).setNegativeButton("取消",null).setNeutralButton("写入预览",(d,w)->previewSQL(sql.getText().toString())).setPositiveButton("只读查询",(d,w)->call(NativeUi.json("op","history.query","sql",sql.getText().toString()),data->new ResultViews(this,this).show("SQL 查询结果",data))).show();}
    private void previewSQL(String sql){call(NativeUi.json("op","history.preview","sql",sql),data->{JSONObject preview=NativeUi.object(data);LinearLayout form=page();form.addView(ui.text("执行前将备份数据库；备份文件名必须不存在",13,NativeUi.MUTED));form.addView(ui.selectable(sql));EditText backup=ui.input("备份文件名","history-backup-"+System.currentTimeMillis()+".sqlite",false);form.addView(backup);form.addView(ui.selectable(NativeUi.pretty(preview)));new AlertDialog.Builder(this).setTitle("确认修改历史数据库").setView(ui.scroll(form)).setNegativeButton("取消",null).setPositiveButton("备份并执行",(d,w)->call(NativeUi.json("op","history.execute","sql",sql,"token",preview.optString("token"),"backup",backup.getText().toString(),"confirmed",true),result->new ResultViews(this,this).show("数据库执行结果",result))).show();});}

    private void renderTools(LinearLayout page){
        LinearLayout c=ui.card();c.addView(ui.title("HTTP 与数据工具",19));c.addView(ui.text("本地转换与预览不会自动执行协议请求",13,NativeUi.MUTED));ui.gap(c,12);c.addView(ui.button("生成当前请求 cURL",false,()->{try{JSONObject request=currentRequest();call(NativeUi.json("op","http.curl","request",request),data->new ResultViews(this,this).show("cURL 预览",NativeUi.object(data).opt("curl")));}catch(Exception e){error(message(e));}}));ui.gap(c,8);c.addView(ui.button("JSON / jq 筛选",false,()->filterHTTP("{}")));ui.gap(c,8);c.addView(ui.button("编码、解码与加解密",false,this::cryptoTool));ui.gap(c,8);c.addView(ui.button("导入其他配置格式",false,this::importFormat));ui.gap(c,8);c.addView(ui.button("HTTP 历史 SQL",false,this::historySQL));page.addView(c);
        LinearLayout modbus=ui.card();modbus.addView(ui.title("Modbus 本地工具",19));modbus.addView(ui.button("类型值 → 寄存器编码",false,this::encodeModbus));ui.gap(modbus,8);modbus.addView(ui.button("查看当前请求规则",false,()->requestUtility("modbus.rules","寄存器规则")));ui.gap(modbus,8);modbus.addView(ui.button("导出当前寄存器注释",false,()->requestUtility("modbus.registers.export","寄存器注释")));ui.gap(modbus,8);modbus.addView(ui.button("导入 MTUI 配置预览",false,()->textTool("MTUI 配置导入预览","modbus.import","source","粘贴 MTUI JSON",true)));ui.gap(modbus,8);modbus.addView(ui.button("读取本机写入审计",false,()->textTool("读取写入审计","modbus.write-log","path","应用私有目录中的文件名",false)));page.addView(modbus);
    }
    private void requestUtility(String op,String title){try{JSONObject request=currentRequest();call(NativeUi.json("op",op,"request",request),data->new ResultViews(this,this).show(title,data));}catch(Exception e){error(message(e));}}
    private void textTool(String title,String op,String key,String hint,boolean multi){EditText input=ui.input(hint,"",multi);new AlertDialog.Builder(this).setTitle(title).setView(input).setNegativeButton("取消",null).setPositiveButton("预览",(d,w)->call(NativeUi.json("op",op,key,input.getText().toString()),data->new ResultViews(this,this).show(title,data))).show();}
    @Override public void filterHTTP(String body){LinearLayout form=page();EditText query=ui.input("jq 查询，例如 .items[] | .name",".",false),data=ui.input("JSON 数据",body,true);form.addView(ui.label("查询表达式"));form.addView(query);form.addView(ui.label("输入数据"));form.addView(data);new AlertDialog.Builder(this).setTitle("JSON 筛选").setView(ui.scroll(form)).setNegativeButton("取消",null).setPositiveButton("筛选",(d,w)->call(NativeUi.json("op","http.filter","query",query.getText().toString(),"data",data.getText().toString()),result->new ResultViews(this,this).show("筛选结果",result))).show();}
    private Spinner picker(LinearLayout form,String label,String[] values){form.addView(ui.label(label));Spinner picker=new Spinner(this);ArrayAdapter<String> adapter=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,values);adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);picker.setAdapter(adapter);form.addView(picker,new LinearLayout.LayoutParams(-1,ui.dp(50)));return picker;}
    private void cryptoTool(){LinearLayout form=page();Spinner algorithm=picker(form,"算法",new String[]{"base64","base64url","aes-128-cbc","aes-192-cbc","aes-256-cbc","aes-128-ecb","aes-192-ecb","aes-256-ecb","none"});Spinner direction=picker(form,"方向",new String[]{"encode","decode"});Spinner encoding=picker(form,"密钥 / IV 编码",new String[]{"text","hex","base64"});EditText key=ui.input("密钥（AES 必填）","",false),iv=ui.input("IV（CBC 必填）","",false),data=ui.input("输入文本","",true);key.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);iv.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);form.addView(ui.label("密钥"));form.addView(key);form.addView(ui.label("IV"));form.addView(iv);form.addView(ui.label("输入数据"));form.addView(data);new AlertDialog.Builder(this).setTitle("本机编码与加解密").setView(ui.scroll(form)).setNegativeButton("取消",null).setPositiveButton("转换",(d,w)->{JSONObject codec=NativeUi.json("algorithm",algorithm.getSelectedItem().toString());try{if(key.length()>0)codec.put("key",NativeUi.json("value",key.getText().toString(),"encoding",encoding.getSelectedItem().toString()));if(iv.length()>0)codec.put("iv",NativeUi.json("value",iv.getText().toString(),"encoding",encoding.getSelectedItem().toString()));}catch(JSONException ignored){}call(NativeUi.json("op","crypto.convert","direction",direction.getSelectedItem().toString(),"codec",codec,"data",data.getText().toString()),result->new ResultViews(this,this).show("转换结果",result));}).show();}
    private void encodeModbus(){LinearLayout form=page();Spinner type=picker(form,"值类型",new String[]{"u16","i16","u32","i32","u64","i64","f32","f64","hex","ascii"});Spinner order=picker(form,"字节顺序",new String[]{"ABCD","BADC","CDAB","DCBA"});EditText value=ui.input("精确数值或文本","",false),address=ui.input("起始地址","0",false);form.addView(ui.label("值（以文本传输，保留 64 位精度）"));form.addView(value);form.addView(ui.label("地址"));form.addView(address);new AlertDialog.Builder(this).setTitle("寄存器编码预览").setView(ui.scroll(form)).setNegativeButton("取消",null).setPositiveButton("编码",(d,w)->{try{call(NativeUi.json("op","modbus.encode","kind",type.getSelectedItem().toString(),"word_order",order.getSelectedItem().toString(),"value",value.getText().toString(),"address",Integer.parseInt(address.getText().toString())),result->new ResultViews(this,this).show("编码后的寄存器（未写入）",result));}catch(NumberFormatException e){error("地址必须是整数");}}).show();}
    private void importFormat(){LinearLayout form=page();Spinner format=picker(form,"源格式",new String[]{"iotools","slumber","v3","rest","openapi","insomnia"});EditText input=ui.input("粘贴源配置","",true);form.addView(input);new AlertDialog.Builder(this).setTitle("配置转换预览").setView(ui.scroll(form)).setNegativeButton("取消",null).setPositiveButton("转换",(d,w)->call(NativeUi.json("op","config.import","source",input.getText().toString(),"format",format.getSelectedItem().toString()),data->{String converted=NativeUi.object(data).optString("source");new AlertDialog.Builder(this).setTitle("转换完成").setMessage("打开转换后的 YAML 草稿可继续检查；只有点按保存才会替换配置。").setNegativeButton("取消",null).setPositiveButton("打开 YAML 草稿",(a,b)->{captureDraft();yamlDraft=converted;yamlDirty=true;tab=1;workspaceTab="yaml";render();}).show();})).show();}

    private void renderSettings(){LinearLayout page=page();heading(page,"设置","本机数据、执行保护与连接设备");LinearLayout protection=ui.card();protection.addView(ui.title("执行保护",19));settingRow(protection,"只读模式","禁止协议写入与历史删除","readonly");settingRow(protection,"保存 HTTP 历史","响应可能包含敏感信息；默认关闭","history");page.addView(protection);
        LinearLayout files=ui.card();files.addView(ui.title("配置与文件",19));files.addView(ui.button("编辑 YAML 配置",false,()->{workspaceTab="yaml";navigate(1);}));ui.gap(files,8);files.addView(ui.button("导入 YAML 配置",false,()->document(Intent.ACTION_OPEN_DOCUMENT,"*/*",null,IMPORT)));ui.gap(files,8);files.addView(ui.button("导出已保存配置",false,this::exportConfig));ui.gap(files,8);files.addView(ui.button("导入证书 / 数据附件",false,()->document(Intent.ACTION_OPEN_DOCUMENT,"*/*",null,IMPORT_FILE)));ui.gap(files,8);files.addView(ui.button("本机文件与导出",false,this::fileInventory));page.addView(files);
        LinearLayout device=ui.card();device.addView(ui.title("USB 串口 · Modbus RTU",19));device.addView(ui.text(UsbSerialTransport.status(),13,NativeUi.MUTED));ui.gap(device,12);device.addView(ui.button("选择 USB 串口",false,this::usbPorts));ui.gap(device,8);device.addView(ui.button("关闭串口",false,()->worker.execute(()->{UsbSerialTransport.close();handler.post(()->{setStatus("USB 串口已关闭",false);render();});})));device.addView(ui.text("需要手机支持 USB Host；串口适配器需另行实机验证",12,NativeUi.MUTED));page.addView(device);
        LinearLayout appearance=ui.card();appearance.addView(ui.title("外观与帮助",19));appearance.addView(ui.button("主题 · "+themeLabel(),false,this::themePicker));ui.gap(appearance,8);appearance.addView(ui.button("使用说明与开源许可",false,this::help));ui.gap(appearance,8);appearance.addView(ui.text("Android 原生视图 · "+Build.SUPPORTED_ABIS[0]+" · Android "+Build.VERSION.RELEASE,12,NativeUi.MUTED));page.addView(appearance);mount(page);
    }
    private void settingRow(LinearLayout parent,String title,String explanation,String key){LinearLayout row=ui.row();LinearLayout text=ui.column();text.addView(ui.title(title,16));text.addView(ui.text(explanation,12,NativeUi.MUTED));row.addView(text,new LinearLayout.LayoutParams(0,-2,1));Switch toggle=new Switch(this);boolean current=getPreferences(0).getBoolean(key,false);toggle.setChecked(current);toggle.setContentDescription(title);final boolean[] reverting={false};toggle.setOnCheckedChangeListener((view,checked)->{if(reverting[0])return;reverting[0]=true;toggle.setChecked(current);reverting[0]=false;String detail=explanation+"。应用此设置会取消当前任务，保留编辑草稿。";confirm((checked?"启用":"关闭")+title,detail,"应用设置",()->{captureDraft();call(NativeUi.json("op","cancel"),ignored->{boolean readOnly=key.equals("readonly")?checked:getPreferences(0).getBoolean("readonly",false);boolean history=key.equals("history")?checked:getPreferences(0).getBoolean("history",false);call(NativeUi.json("op","options.set","options",NativeUi.json("read_only",readOnly,"history",history)),data->{getPreferences(0).edit().putBoolean(key,checked).apply();state=NativeUi.object(data);setStatus("设置已生效 · 草稿保留",false);render();});});});});row.setPadding(0,ui.dp(14),0,ui.dp(14));row.addView(toggle);parent.addView(row);}
    private void usbPorts(){JSONArray ports;try{ports=UsbSerialTransport.listPorts();}catch(IOException e){error(message(e));return;}if(ports.length()==0){new AlertDialog.Builder(this).setTitle("未发现 USB 串口").setMessage("连接受支持的 USB 串口适配器后重新打开。此页面只枚举本机设备，不扫描网络。").setPositiveButton("知道了",null).show();return;}String[] labels=new String[ports.length()];for(int i=0;i<labels.length;i++)labels[i]=ports.optJSONObject(i).optString("label");new AlertDialog.Builder(this).setTitle("选择 USB 串口").setItems(labels,(d,index)->usbSettings(ports.optJSONObject(index))).setNegativeButton("取消",null).show();}
    private void usbSettings(JSONObject port){String endpoint=port.optString("endpoint");LinearLayout form=page();form.addView(ui.text(endpoint,14,NativeUi.INK));EditText baud=ui.input("波特率","9600",false);baud.setInputType(InputType.TYPE_CLASS_NUMBER);form.addView(ui.label("波特率"));form.addView(baud);Spinner stop=picker(form,"停止位",new String[]{"1","2"}),parity=picker(form,"校验",new String[]{"N","E","O"});form.addView(ui.text("Modbus RTU 使用 8 数据位。打开串口不会自动发送请求",13,NativeUi.MUTED));new AlertDialog.Builder(this).setTitle("配置 USB 串口").setView(ui.scroll(form)).setNegativeButton("取消",null).setNeutralButton("仅复制地址",(d,w)->copyText("USB 地址",endpoint)).setPositiveButton(port.optBoolean("permission")?"打开串口":"申请设备权限",(d,w)->{try{if(!UsbSerialTransport.requestPermission(endpoint)){setStatus("请在系统对话框授权，然后再次打开串口",false);return;}int b=Integer.parseInt(baud.getText().toString()),s=Integer.parseInt(stop.getSelectedItem().toString());String p=parity.getSelectedItem().toString();worker.execute(()->{try{UsbSerialTransport.open(endpoint,b,8,s,p);handler.post(()->{setStatus("串口已打开 · 请求地址 "+endpoint,false);confirm("串口已就绪","将此地址用于新的 Modbus 读取草稿？","创建读取草稿",()->selectRequest(NativeUi.json("id","usb-modbus-"+System.currentTimeMillis(),"name","USB Modbus RTU","protocol","modbus","action","read-holding","endpoint",endpoint,"timeout","5s","params",NativeUi.json("unit",1,"address",0,"count",10,"baud",b,"data_bits",8,"stop_bits",s,"parity",p))));});}catch(Exception e){handler.post(()->error(message(e)));}});}catch(Exception e){error(message(e));}}).show();}

    private String themeLabel(){String theme=getPreferences(0).getString("theme","dark");return theme.equals("dark")?"深色":theme.equals("light")?"浅色":"跟随系统";}
    private void themePicker(){String[] labels={"深色","浅色","跟随系统"},values={"dark","light","system"};new AlertDialog.Builder(this).setTitle("选择主题").setItems(labels,(d,index)->{captureDraft();getPreferences(0).edit().putString("theme",values[index]).apply();applyTheme();buildShell();render();}).setNegativeButton("取消",null).show();}
    private boolean themeIsDark(){String theme=getPreferences(0).getString("theme","dark");return theme.equals("dark")||(theme.equals("system")&&(getResources().getConfiguration().uiMode&Configuration.UI_MODE_NIGHT_MASK)==Configuration.UI_MODE_NIGHT_YES);}
    private void applyTheme(){boolean dark=themeIsDark();setTheme(dark?R.style.AppTheme:R.style.AppThemeLight);NativeUi.theme(dark);getWindow().setStatusBarColor(NativeUi.BG);getWindow().setNavigationBarColor(NativeUi.CARD);getWindow().getDecorView().setSystemUiVisibility(dark?0:View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);}
    private void document(String action,String mime,String title,int request){Intent intent=new Intent(action).setType(mime).addCategory(Intent.CATEGORY_OPENABLE);if(title!=null)intent.putExtra(Intent.EXTRA_TITLE,title);try{startActivityForResult(intent,request);}catch(ActivityNotFoundException e){error("系统没有可用的文件选择器");}}
    private void exportConfig(){document(Intent.ACTION_CREATE_DOCUMENT,"application/yaml","iotools.yaml",EXPORT);}
    @Override public void exportText(String title,String text){exportText=text;document(Intent.ACTION_CREATE_DOCUMENT,"application/octet-stream",title,EXPORT_TEXT);}
    private void fileInventory(){File[] files=getFilesDir().listFiles(File::isFile);if(files==null||files.length==0){toast("本机目录没有文件");return;}Arrays.sort(files,Comparator.comparing(File::getName));String[] names=new String[files.length];for(int i=0;i<files.length;i++)names[i]=files[i].getName()+"  ·  "+files[i].length()+" B";new AlertDialog.Builder(this).setTitle("选择本机文件").setItems(names,(d,index)->{File file=files[index];new AlertDialog.Builder(this).setTitle(file.getName()).setMessage("文件位于应用私有目录，导出后会交给你选择的位置。\n\n"+file.getAbsolutePath()).setNegativeButton("关闭",null).setNeutralButton("复制路径",(dialog,which)->copyText("文件路径",file.getAbsolutePath())).setPositiveButton("导出文件",(dialog,which)->{exportSource=file;document(Intent.ACTION_CREATE_DOCUMENT,"application/octet-stream",file.getName(),EXPORT_FILE);}).show();}).setNegativeButton("关闭",null).show();}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri uri=data.getData();worker.execute(()->{try{
        if(request==EXPORT_TEXT){String value=exportText;if(value==null)throw new IOException("没有待导出的内容");try(OutputStream out=getContentResolver().openOutputStream(uri,"w")){if(out==null)throw new IOException("无法打开目标");out.write(value.getBytes(StandardCharsets.UTF_8));}handler.post(()->setStatus("内容已导出",false));return;}
        if(request==EXPORT||request==EXPORT_FILE){File file=request==EXPORT?config:exportSource;if(file==null)throw new IOException("未选择文件");try(InputStream in=new FileInputStream(file);OutputStream out=getContentResolver().openOutputStream(uri,"w")){if(out==null)throw new IOException("无法打开目标");copy(in,out,64<<20);}handler.post(()->setStatus("文件已导出到所选位置",false));return;}
        if(request==IMPORT_FILE){String name="data.bin";try(android.database.Cursor cursor=getContentResolver().query(uri,new String[]{android.provider.OpenableColumns.DISPLAY_NAME},null,null,null)){if(cursor!=null&&cursor.moveToFirst())name=cursor.getString(0);}if(name==null)name="data.bin";name=name.replace('/','_').replace('\\','_').replaceAll("[\\p{Cntrl}]","_");if(name.length()>80)name=name.substring(name.length()-80);File attachment=File.createTempFile("attachment-","-"+name,getFilesDir());boolean done=false;try(InputStream in=getContentResolver().openInputStream(uri);OutputStream out=new FileOutputStream(attachment)){if(in==null)throw new IOException("无法读取附件");copy(in,out,32<<20);done=true;}finally{if(!done)attachment.delete();}handler.post(()->new AlertDialog.Builder(this).setTitle("附件已导入").setMessage("可在证书、密钥或数据文件字段引用此路径：\n\n"+attachment.getAbsolutePath()).setNegativeButton("关闭",null).setPositiveButton("复制路径",(d,w)->copyText("附件路径",attachment.getAbsolutePath())).show());return;}
        if(request==IMPORT){ByteArrayOutputStream bytes=new ByteArrayOutputStream();try(InputStream in=getContentResolver().openInputStream(uri)){if(in==null)throw new IOException("无法读取配置");copy(in,bytes,4<<20);}String imported=bytes.toString("UTF-8");unwrap(NativeRuntime.command(NativeUi.json("op","config.validate","source",imported).toString()));handler.post(()->confirm("导入并替换配置","文件已通过校验。替换会清除未保存草稿，并在本机保留当前配置备份。不会自动执行请求。","备份并替换",()->{captureDraft();worker.execute(()->{try{if(config.exists()){File backup=File.createTempFile("iotools-backup-",".yaml",getFilesDir());try(InputStream in=new FileInputStream(config);OutputStream out=new FileOutputStream(backup)){copy(in,out,4<<20);}}unwrap(NativeRuntime.command(NativeUi.json("op","config.save","source",imported).toString()));handler.post(()->{drafts.clear();yamlDraft=imported;source=imported;yamlDirty=false;selected=null;selectedKey="";tab=0;refreshState(()->{setStatus("配置已导入并备份",false);render();});});}catch(Exception error){handler.post(()->error(message(error)));}});}));}
    }catch(Exception e){handler.post(()->error("文件操作失败："+message(e)));}});}
    private static void copy(InputStream in,OutputStream out,int max)throws IOException{byte[] buf=new byte[8192];int n,total=0;while((n=in.read(buf))!=-1){total+=n;if(total>max)throw new IOException("文件超过 "+(max/(1<<20))+" MiB 限制");out.write(buf,0,n);}}
    private void copyText(String label,String text){((ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText(label,text));toast("已复制");}
    private void help(){LinearLayout page=page();page.addView(ui.title("iotools 使用说明",24));String[] titles={"请求与环境","原生编辑与结果","安全执行","文件与隐私","后台与草稿","连接设备"};String[] bodies={"在请求页筛选 HTTP、Kafka、MQTT、Modbus、OPC UA。选择环境只改变变量；只有点按执行才会连接目标。127.0.0.1 表示这台 Android 设备。","工作台提供原生表单、完整 YAML 与结构化结果。更多参数包含认证、TLS、数据格式和各协议高级选项。结果中的主题、节点按钮准备新的草稿，检查后再执行。","写入、删除与方法调用需确认具体目标；只读模式由本机引擎强制限制。请求中的依赖、模板选择和敏感操作会通过原生对话框单独询问。","配置、证书与历史均位于应用私有目录。通过系统文件选择器导入导出。HTTP 历史默认关闭。YAML、响应与导出文件可能含敏感信息，请按需打开。","进入后台会取消活动请求及订阅，恢复后不会重放。未保存草稿在本次应用进程内保留；系统结束进程后需从已保存配置重新开始。请明确保存重要修改。","支持 TCP、TLS、RTU over TCP 与经授权的 USB 串口适配器。USB 设备需手机支持 USB Host，选择、授权和打开均为独立动作；不会自动探测工业设备。"};for(int i=0;i<titles.length;i++){LinearLayout c=ui.card();c.addView(ui.title(titles[i],17));c.addView(ui.text(bodies[i],14,NativeUi.MUTED));page.addView(c);}page.addView(ui.button("开源许可",false,()->assetText("LICENSE","开源许可")));ui.gap(page,8);page.addView(ui.button("第三方声明",false,()->assetText("NOTICE.txt","第三方声明")));new AlertDialog.Builder(this).setView(ui.scroll(page)).setPositiveButton("关闭",null).show();}
    private void assetText(String file,String title){worker.execute(()->{try(InputStream input=getAssets().open(file);ByteArrayOutputStream out=new ByteArrayOutputStream()){copy(input,out,4<<20);String value=out.toString("UTF-8");handler.post(()->new ResultViews(this,this).show(title,value));}catch(IOException error){handler.post(()->error("未找到 "+file+"，请查看项目发行包中的开源许可文件"));}});}
    private interface Success {void accept(Object data);}
    private interface Failure {void accept(String message);}
    private void call(JSONObject request,Success success){call(request,success,error->error(error));}
    private void call(JSONObject request,Success success,Failure failure){if(destroyed)return;worker.execute(()->{try{Object result=unwrap(NativeRuntime.command(request.toString()));handler.post(()->{if(!destroyed)success.accept(result);});}catch(Throwable error){handler.post(()->{if(!destroyed)failure.accept(message(error));});}});}
    private static Object unwrap(String reply)throws JSONException,IOException{JSONObject envelope=ExactJson.object(reply);if(!envelope.optBoolean("ok"))throw new IOException(envelope.optString("error","本机引擎返回错误"));return envelope.opt("data");}
    private void refreshState(Runnable done){call(NativeUi.json("op","state"),data->{state=NativeUi.object(data);running=state.optBoolean("running");if(done!=null)done.run();});}
    private void refreshSource(Runnable done){call(NativeUi.json("op","config.get"),data->{source=NativeUi.object(data).optString("source");if(!yamlDirty)yamlDraft=source;if(done!=null)done.run();});}
    private void setStatus(String text,boolean error){status=text;if(statusView!=null){statusView.setText(text);statusView.setTextColor(error?NativeUi.DANGER:NativeUi.MUTED);}}
    private void error(String text){setStatus(text,true);if(!isFinishing()&&active)new AlertDialog.Builder(this).setTitle("操作未完成").setMessage(text).setPositiveButton("知道了",null).show();}
    private static String message(Throwable error){return error.getMessage()==null?error.getClass().getSimpleName():error.getMessage();}
    private void toast(String text){Toast.makeText(this,text,Toast.LENGTH_SHORT).show();}
    private void confirm(String title,String body,String action,Runnable confirmed){new AlertDialog.Builder(this).setTitle(title).setMessage(body).setNegativeButton("取消",null).setPositiveButton(action,(d,w)->confirmed.run()).show();}
    private void hideKeyboard(){View focused=getCurrentFocus();if(focused!=null)((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(focused.getWindowToken(),0);}
    private void restore(Bundle saved){tab=saved.getInt("tab",0);workspaceTab=saved.getString("workspaceTab","form");selectedKey=saved.getString("selectedKey","");protocolFilter=saved.getString("filter","all");}
    @Override protected void onSaveInstanceState(Bundle state){captureDraft();state.putInt("tab",tab);state.putString("workspaceTab",workspaceTab);state.putString("selectedKey",selectedKey);state.putString("filter",protocolFilter);super.onSaveInstanceState(state);}
    @Override public void onConfigurationChanged(Configuration configuration){captureDraft();super.onConfigurationChanged(configuration);applyTheme();buildShell();render();}
    @Override protected void onStart(){super.onStart();active=true;UsbSerialTransport.resume();if(ready){NativeRuntime.resume();handler.removeCallbacks(poll);handler.post(poll);}}
    @Override protected void onStop(){captureDraft();active=false;handler.removeCallbacks(poll);NativeRuntime.pause();UsbSerialTransport.pause();if(running){running=false;setStatus("后台已取消活动任务 · 草稿保留",false);}super.onStop();}
    @Override protected void onDestroy(){destroyed=true;handler.removeCallbacksAndMessages(null);worker.shutdown();if(isFinishing()){NativeRuntime.close();UsbSerialTransport.shutdown();}super.onDestroy();}
    @Override public void onBackPressed(){if(tab!=0){navigate(0);return;}super.onBackPressed();}
}
