package io.github.liveyum.iotools;

import android.app.AlertDialog;
import android.content.Context;
import android.graphics.Typeface;
import android.view.View;
import android.widget.*;
import org.json.*;
import java.util.*;

/** Protocol-aware result cards consume only real engine events. */
final class ResultViews {
    interface Actions { void prepare(String action,String key,Object value); void filterHTTP(String body); void exportText(String title,String text); void rerun(); void fullResult(String id); String resultProtocol(); String resultAction(); String resultParameter(String key); void prepareParams(String action,JSONObject patch); }
    private final NativeUi ui;
    private final Actions actions;
    ResultViews(Context c,Actions a){ui=new NativeUi(c);actions=a;}

    View event(JSONObject event){
        String kind=event.optString("kind");Object raw=event.opt("data");JSONObject data=NativeUi.object(raw);
        LinearLayout card=ui.card();LinearLayout head=ui.row();String title=label(kind);
        TextView caption=ui.title(title,16);head.addView(caption,new LinearLayout.LayoutParams(0,-2,1));String time=event.optString("time");if(time.length()>19)time=time.substring(11,19);head.addView(ui.text(time,11,NativeUi.MUTED));card.addView(head);ui.gap(card,10);
        if(data.optBoolean("truncated")&&!data.optString("result_id").isEmpty()){card.addView(ui.text("结果较大 · "+data.optLong("original_bytes")+" 字节",13,NativeUi.MUTED));card.addView(ui.selectable(data.optString("preview")));card.addView(ui.button("查看完整结果 / 导出",false,()->actions.fullResult(data.optString("result_id"))));return card;}
        if(kind.equals("response")||kind.equals("transformed")){
            int status=data.optInt("status");TextView badge=ui.title("HTTP "+status,24);badge.setTextColor(status>=400?NativeUi.DANGER:NativeUi.ACCENT);card.addView(badge);
            Object body=data.opt("body");if(actions.resultProtocol().equals("kafka"))kafkaDirectory(card,body);LinearLayout tabs=ui.row(),bodyView=ui.column();String[] modes={"正文","响应头","原始数据"};for(int mode=0;mode<3;mode++){int chosen=mode;tabs.addView(ui.chip(modes[mode],mode==0,()->{bodyView.removeAllViews();if(chosen==0)tree(bodyView,body,0);else if(chosen==1)tree(bodyView,data.opt("headers"),0);else {String encoded=data.optString("raw_body_base64");if(!encoded.isEmpty()){try{String text=new String(android.util.Base64.decode(encoded,android.util.Base64.DEFAULT),java.nio.charset.StandardCharsets.UTF_8);bodyView.addView(ui.selectable(shortText(text,16000)));details(bodyView,"完整原始字节 Base64",encoded);}catch(Exception error){tree(bodyView,encoded,0);}}else tree(bodyView,body,0);}}));}card.addView(ui.chips(tabs));ui.gap(card,10);card.addView(bodyView);tree(bodyView,body,0);
            LinearLayout common=ui.row();ui.weighted(common,ui.button("复制",false,()->{((android.content.ClipboardManager)ui.context.getSystemService(Context.CLIPBOARD_SERVICE)).setPrimaryClip(android.content.ClipData.newPlainText("响应正文",NativeUi.pretty(body)));Toast.makeText(ui.context,"已复制",Toast.LENGTH_SHORT).show();}));ui.weighted(common,ui.button("重新执行",false,actions::rerun));card.addView(common);ui.gap(card,8);LinearLayout controls=ui.row();ui.weighted(controls,ui.button("筛选响应",false,()->actions.filterHTTP(NativeUi.pretty(body))));ui.weighted(controls,ui.button("导出响应",false,()->actions.exportText("response.json",NativeUi.pretty(body))));ui.gap(card,12);card.addView(controls);
        }else if(kind.equals("message")||kind.equals("record")){
            card.addView(ui.title(data.optString("topic","消息"),18));
            if(kind.equals("record")){ui.pair(card,"分区 / 偏移",data.optString("partition")+" / "+data.optString("offset"));ui.pair(card,"消息键",data.optString("key"));tree(card,data.opt("value"),0);}
            else {ui.pair(card,"QoS / 保留",data.optString("qos")+" / "+(data.optBoolean("retained")?"是":"否"));ui.pair(card,"字节数",data.optString("bytes"));tree(card,data.has("payload_json")?data.opt("payload_json"):data.has("payload_messagepack")?data.opt("payload_messagepack"):data.opt("payload"),0);details(card,"十六进制 / 原始内容",data);}
            String topic=data.optString("topic");if(!topic.isEmpty()){ui.gap(card,10);card.addView(ui.button("以此主题创建"+(kind.equals("record")?"消费":"订阅")+"草稿",false,()->actions.prepare(kind.equals("record")?"consume":"subscribe","topic",topic)));}
        }else if(kind.equals("reference")){
            String node=nodeID(data),name=first(data,"display_name","browse_name","DisplayName","BrowseName");card.addView(ui.title(name.isEmpty()?node:name,18));ui.pair(card,"节点",node);ui.pair(card,"类型",first(data,"node_class","NodeClass"));
            if(!node.isEmpty()){
                LinearLayout row=ui.row();ui.weighted(row,ui.button("浏览子节点",false,()->actions.prepare("browse","node_id",node)));ui.weighted(row,ui.button("读取",false,()->actions.prepare("read","node_id",node)));card.addView(row);ui.gap(card,8);LinearLayout row2=ui.row();ui.weighted(row2,ui.button("属性",false,()->actions.prepare("attributes","node_id",node)));ui.weighted(row2,ui.button("订阅",false,()->actions.prepare("subscribe","node_id",node)));ui.weighted(row2,ui.button("写入",false,()->actions.prepare("write","node_id",node)));card.addView(row2);
            }
            if(first(data,"node_class","NodeClass").toLowerCase(Locale.ROOT).contains("method")){ui.gap(card,8);LinearLayout methods=ui.row();ui.weighted(methods,ui.button("读取方法签名",false,()->actions.prepareParams("method-arguments",NativeUi.json("method_id",node,"object_id",actions.resultParameter("node_id")))));ui.weighted(methods,ui.button("准备方法调用",false,()->actions.prepareParams("call",NativeUi.json("method_id",node,"object_id",actions.resultParameter("node_id")))));card.addView(methods);}details(card,"引用详情",data);
        }else if(kind.equals("topics")&&raw instanceof JSONObject){
            ArrayList<String> keys=new ArrayList<>();Iterator<String> iterator=data.keys();while(iterator.hasNext())keys.add(iterator.next());Collections.sort(keys);
            for(String topic:keys){LinearLayout topicRow=ui.column();topicRow.setPadding(0,ui.dp(8),0,ui.dp(8));topicRow.addView(ui.title(topic,16));Object value=data.opt(topic);JSONObject detail=NativeUi.object(value);ui.pair(topicRow,"分区",String.valueOf(NativeUi.object(detail.opt("Partitions")).length()));LinearLayout controls=ui.row();ui.weighted(controls,ui.button("消费消息",false,()->actions.prepare("consume","topic",topic)));ui.weighted(controls,ui.button("主题配置",false,()->actions.prepare("topic-config","topic",topic)));topicRow.addView(controls);details(topicRow,"主题详情",value);card.addView(topicRow);}
        }else if(kind.equals("retained-preview")){JSONArray topics=NativeUi.array(data.opt("topics"));card.addView(ui.text(data.optString("warning"),13,NativeUi.DANGER));ui.pair(card,"本次精确主题",String.valueOf(topics.length()));for(int i=0;i<Math.min(topics.length(),100);i++)card.addView(ui.selectable(topics.optString(i)));card.addView(ui.button("准备清理这些保留主题",false,()->actions.prepareParams("clean-retained",NativeUi.json("confirm_topics",topics,"confirm_token",data.optString("confirm_token")))));
        }else if(kind.equals("method-arguments")){tree(card,data,0);JSONArray inputs=NativeUi.array(data.opt("inputs"));JSONArray arguments=new JSONArray();for(int i=0;i<inputs.length();i++){JSONObject input=inputs.optJSONObject(i);if(input!=null)arguments.put(NativeUi.json("type",input.optString("type"),"value",""));}card.addView(ui.button("填写参数并准备调用",false,()->actions.prepareParams("call",NativeUi.json("method_id",data.optString("method_id"),"arguments",arguments))));
        }else if((kind.equals("groups")||kind.equals("group")||kind.equals("lag"))&&raw instanceof JSONObject){Iterator<String> groups=data.keys();while(groups.hasNext()){String group=groups.next();LinearLayout item=ui.column();item.addView(ui.title(group,17));LinearLayout controls=ui.row();ui.weighted(controls,ui.button("成员",false,()->actions.prepare("group","group",group)));ui.weighted(controls,ui.button("消费滞后",false,()->actions.prepare("lag","group",group)));ui.weighted(controls,ui.button("删除草稿",false,()->actions.prepare("delete-group","group",group)));item.addView(controls);details(item,"当前组详情",data.opt(group));ui.gap(item,12);card.addView(item);}
        }else if(kind.equals("registers")&&raw instanceof JSONArray){
            JSONArray rows=(JSONArray)raw;ui.pair(card,"本次返回",rows.length()+" 个寄存器");HorizontalScrollView horizontal=new HorizontalScrollView(ui.context);LinearLayout table=ui.column();String[] columns={"address","u16","i16","hex","f32","ascii"};LinearLayout header=ui.row();for(String key:columns){TextView t=ui.title(key.equals("address")?"地址":key,12);t.setPadding(ui.dp(8),ui.dp(8),ui.dp(8),ui.dp(8));header.addView(t,new LinearLayout.LayoutParams(ui.dp(key.equals("f32")?118:80),-2));}header.setBackgroundColor(NativeUi.TINT);table.addView(header);
            for(int i=0;i<Math.min(rows.length(),16);i++){JSONObject value=rows.optJSONObject(i);if(value==null)continue;LinearLayout line=ui.row();for(String key:columns){TextView t=ui.selectable(value.optString(key,"·"));t.setPadding(ui.dp(8),ui.dp(10),ui.dp(8),ui.dp(10));line.addView(t,new LinearLayout.LayoutParams(ui.dp(key.equals("f32")?118:80),-2));}line.setOnClickListener(v->show("寄存器 "+value.optString("address"),value));table.addView(line);}horizontal.addView(table);card.addView(horizontal);card.addView(ui.text("点按行查看全部解码格式",12,NativeUi.MUTED));if(rows.length()>16)card.addView(ui.button("查看全部 "+rows.length()+" 行",false,()->registerRows(rows)));
        }else if(kind.equals("endpoint")){
            card.addView(ui.title(data.optString("url"),16));ui.pair(card,"安全策略",data.optString("security_policy"));ui.pair(card,"消息模式",data.optString("security_mode"));ui.pair(card,"证书指纹",data.optString("certificate_sha256"));card.addView(ui.text("发现结果仅为服务端声明，请核对证书指纹后配置连接",12,NativeUi.MUTED));details(card,"端点详情",data);
        }else if(kind.equals("error")||kind.equals("failed")){
            caption.setTextColor(NativeUi.DANGER);TextView error=ui.text(errorText(raw),14,NativeUi.DANGER);error.setTextIsSelectable(true);card.addView(error);
        }else if(kind.equals("value")||kind.equals("notification")||kind.equals("attribute")){
            ui.pair(card,"节点",data.optString("node_id"));ui.pair(card,"状态",data.optString("status"));tree(card,data.has("value")?data.opt("value"):data,0);details(card,"数据详情",data);
        }else tree(card,raw,0);
        return card;
    }
    private void kafkaDirectory(LinearLayout card,Object body){String action=actions.resultAction();if(action.equals("schemas")&&body instanceof JSONArray){JSONArray names=(JSONArray)body;for(int i=0;i<Math.min(names.length(),100);i++){String subject=names.optString(i);LinearLayout item=ui.column();item.addView(ui.title(subject,17));LinearLayout buttons=ui.row();ui.weighted(buttons,ui.button("版本",false,()->actions.prepare("schema-versions","subject",subject)));ui.weighted(buttons,ui.button("最新 Schema",false,()->actions.prepareParams("schema",NativeUi.json("subject",subject,"version","latest"))));ui.weighted(buttons,ui.button("删除草稿",false,()->actions.prepareParams("delete-subject",NativeUi.json("subject",subject,"confirm_subject",subject))));item.addView(buttons);card.addView(item);}}
        else if(action.equals("schema-versions")&&body instanceof JSONArray){JSONArray versions=(JSONArray)body;for(int i=0;i<Math.min(versions.length(),100);i++){String version=versions.optString(i);String subject=actions.resultParameter("subject");LinearLayout row=ui.row();ui.weighted(row,ui.button("版本 "+version,false,()->actions.prepareParams("schema",NativeUi.json("subject",subject,"version",version))));ui.weighted(row,ui.button("准备删除",false,()->actions.prepareParams("delete-schema",NativeUi.json("subject",subject,"version",version,"confirm_subject",subject))));card.addView(row);}}
        else if(action.equals("connectors")){ArrayList<String> names=new ArrayList<>();if(body instanceof JSONObject){Iterator<String> iterator=((JSONObject)body).keys();while(iterator.hasNext())names.add(iterator.next());}else if(body instanceof JSONArray){JSONArray array=(JSONArray)body;for(int i=0;i<array.length();i++)names.add(array.optString(i));}Collections.sort(names);for(String name:names){LinearLayout item=ui.column();item.addView(ui.title(name,17));LinearLayout controls=ui.row();ui.weighted(controls,ui.button("状态",false,()->actions.prepare("connector","connector",name)));ui.weighted(controls,ui.button("暂停",false,()->actions.prepare("pause-connector","connector",name)));ui.weighted(controls,ui.button("恢复",false,()->actions.prepare("resume-connector","connector",name)));item.addView(controls);item.addView(ui.button("准备删除连接器",false,()->actions.prepare("delete-connector","connector",name)));ui.gap(item,12);card.addView(item);}}
    }
    private void registerRows(JSONArray rows){ListView list=new ListView(ui.context);list.setAdapter(new BaseAdapter(){public int getCount(){return rows.length();}public Object getItem(int p){return rows.opt(p);}public long getItemId(int p){return p;}public View getView(int position,View recycled,android.view.ViewGroup parent){TextView text=recycled instanceof TextView?(TextView)recycled:ui.text("",14,NativeUi.INK);JSONObject row=NativeUi.object(rows.opt(position));text.setText("地址 "+row.optString("address")+"   U16 "+row.optString("u16")+"   "+row.optString("hex"));text.setPadding(ui.dp(20),ui.dp(14),ui.dp(20),ui.dp(14));return text;}});list.setOnItemClickListener((parent,view,position,id)->show("寄存器详情",rows.opt(position)));new AlertDialog.Builder(ui.context).setTitle("寄存器 · "+rows.length()+" 行").setView(list).setPositiveButton("关闭",null).setNeutralButton("导出",(d,w)->actions.exportText("registers.json",NativeUi.pretty(rows))).show();}
    private String errorText(Object raw){JSONObject data=NativeUi.object(raw);return data.optString("error",data.optString("message",NativeUi.pretty(raw)));}
    private String first(JSONObject object,String... keys){for(String key:keys){Object v=object.opt(key);if(v instanceof JSONObject){JSONObject o=(JSONObject)v;String s=o.optString("Text",o.optString("Name",""));if(!s.isEmpty())return s;}else if(v!=null&&v!=JSONObject.NULL&&!String.valueOf(v).isEmpty())return String.valueOf(v);}return "";}
    private String nodeID(JSONObject data){String direct=first(data,"node_id","NodeID");if(!direct.isEmpty()&&!direct.startsWith("{"))return direct;JSONObject n=data.optJSONObject("NodeID");if(n!=null)return n.optString("NodeID",n.optString("node_id",""));return "";}
    private void tree(LinearLayout parent,Object raw,int depth){
        if(raw instanceof JSONObject){JSONObject o=(JSONObject)raw;Iterator<String> keys=o.keys();int count=0;while(keys.hasNext()&&count++<60){String key=keys.next();Object v=o.opt(key);if(v instanceof JSONObject||v instanceof JSONArray)details(parent,key,v);else ui.pair(parent,key,shortText(NativeUi.pretty(v),3000));}if(keys.hasNext())details(parent,"更多字段",raw);}
        else if(raw instanceof JSONArray){JSONArray a=(JSONArray)raw;if(a.length()==0)parent.addView(ui.text("空列表",14,NativeUi.MUTED));for(int i=0;i<Math.min(a.length(),30);i++){Object value=a.opt(i);if(value instanceof JSONObject||value instanceof JSONArray)details(parent,"第 "+(i+1)+" 项",value);else parent.addView(ui.selectable(NativeUi.pretty(value)));}if(a.length()>30)details(parent,"全部 "+a.length()+" 项",raw);}
        else {String value=NativeUi.pretty(raw);parent.addView(ui.selectable(shortText(value,12000)));if(value.length()>12000)details(parent,"查看完整内容",raw);}
    }
    void details(LinearLayout parent,String title,Object value){Button button=ui.button(title+"  ›",false,()->show(title,value));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=ui.dp(8);parent.addView(button,p);}
    void show(String title,Object value){LinearLayout content=ui.column();content.setPadding(ui.dp(20),ui.dp(8),ui.dp(20),ui.dp(20));String full=NativeUi.pretty(value);TextView text=ui.selectable(shortText(full,65536));content.addView(text);if(full.length()>65536)content.addView(ui.text("屏幕显示前 64 KiB；导出包含完整数据",13,NativeUi.MUTED));new AlertDialog.Builder(ui.context).setTitle(title).setView(ui.scroll(content)).setPositiveButton("关闭",null).setNeutralButton("导出",(d,w)->actions.exportText("result.json",NativeUi.pretty(value))).show();}
    private String shortText(String s,int max){return s.length()>max?s.substring(0,max)+"\n…":s;}
    private String label(String kind){switch(kind){case "response":return "HTTP 响应";case "transformed":return "转换结果";case "message":return "MQTT 消息";case "record":return "Kafka 消息";case "reference":return "OPC UA 节点";case "registers":return "寄存器数据";case "topics":return "Kafka 主题";case "endpoint":return "发现的端点";case "notification":return "订阅通知";case "value":return "读取值";case "attribute":return "节点属性";case "error":case "failed":return "执行错误";case "done":case "complete":case "completed":return "执行结束";case "cancelled":return "已取消";case "started":return "开始执行";default:return kind;}}
}
