package io.github.liveyum.iotools;

import android.app.AlertDialog;
import android.content.Context;
import android.view.View;
import android.widget.*;
import org.json.*;
import java.math.*;
import java.util.*;

/** Bounded topic history and native value charts drawn only from received messages. */
final class TopicHistory {
    private static final class Sample {final String time,text;final BigDecimal value;Sample(String time,String text,BigDecimal value){this.time=time;this.text=text;this.value=value;}}
    static void show(Context context,List<JSONObject> received,String topic,ResultViews.Actions actions){
        NativeUi ui=new NativeUi(context);ArrayList<JSONObject> history=new ArrayList<>();for(JSONObject event:received){JSONObject data=NativeUi.object(event.opt("data"));if(topic.equals(data.optString("topic")))history.add(event);}while(history.size()>100)history.remove(0);
        LinearLayout page=ui.column();page.setPadding(ui.dp(20),ui.dp(10),ui.dp(20),ui.dp(16));page.addView(ui.title(topic,20));page.addView(ui.text("缓存最近 "+history.size()+" 条该主题消息。保留消息回放与无效值不进入趋势",13,NativeUi.MUTED));
        TreeMap<String,ArrayList<Sample>> series=new TreeMap<>();for(JSONObject event:history){JSONObject data=NativeUi.object(event.opt("data"));if(data.optBoolean("retained"))continue;Object payload=data.has("payload_json")?data.opt("payload_json"):data.has("payload_messagepack")?data.opt("payload_messagepack"):data.has("payload")?data.opt("payload"):data.opt("value");if(payload instanceof String){try{payload=ExactJson.parse((String)payload);}catch(Exception ignored){}}collect(series,"$",payload,event.optString("time"),0);}
        if(!series.isEmpty()){page.addView(ui.label("趋势字段（JSON / MessagePack 路径）"));Spinner fields=new Spinner(context);ArrayList<String> names=new ArrayList<>(series.keySet());ArrayAdapter<String> adapter=new ArrayAdapter<>(context,android.R.layout.simple_spinner_item,names);adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);fields.setAdapter(adapter);page.addView(fields,new LinearLayout.LayoutParams(-1,ui.dp(50)));LinearLayout chart=ui.card();page.addView(chart);fields.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> parent){}public void onItemSelected(AdapterView<?> parent,View view,int position,long id){draw(ui,chart,series.get(names.get(position)));}});draw(ui,chart,series.get(names.get(0)));}
        else page.addView(ui.text("当前消息没有可绘制的数值；仍可查看并导出完整载荷",13,NativeUi.MUTED));
        ResultViews renderer=new ResultViews(context,actions);for(int i=history.size()-1;i>=Math.max(0,history.size()-30);i--)page.addView(renderer.event(history.get(i)));if(history.size()>30)page.addView(ui.text("显示最近 30 条消息；导出包含此主题全部已保留记录",12,NativeUi.MUTED));new AlertDialog.Builder(context).setTitle("主题历史与趋势").setView(ui.scroll(page)).setNegativeButton("关闭",null).setPositiveButton("导出主题",(d,w)->actions.exportText("topic-messages.json",NativeUi.pretty(new JSONArray(history)))).show();
    }
    private static void collect(Map<String,ArrayList<Sample>> output,String path,Object raw,String time,int depth){if(depth>6||output.size()>128||raw==null||raw==JSONObject.NULL)return;if(raw instanceof JSONObject){JSONObject object=(JSONObject)raw;if(object.has("messagepack_type"))return;Iterator<String> keys=object.keys();while(keys.hasNext()){String key=keys.next();collect(output,path+"."+key,object.opt(key),time,depth+1);}return;}if(raw instanceof JSONArray){JSONArray array=(JSONArray)raw;add(output,path+".length",time,String.valueOf(array.length()),new BigDecimal(array.length()));for(int i=0;i<Math.min(array.length(),32);i++)collect(output,path+"["+i+"]",array.opt(i),time,depth+1);return;}if(raw instanceof Boolean){add(output,path,time,String.valueOf(raw),Boolean.TRUE.equals(raw)?BigDecimal.ONE:BigDecimal.ZERO);return;}String text=String.valueOf(raw).trim();try{if(text.length()>10000)return;BigDecimal value=new BigDecimal(text);add(output,path,time,text,value);}catch(NumberFormatException ignored){}}
    private static void add(Map<String,ArrayList<Sample>> output,String path,String time,String text,BigDecimal number){ArrayList<Sample> samples=output.get(path);if(samples==null){samples=new ArrayList<>();output.put(path,samples);}samples.add(new Sample(time,text,number));}
    private static void draw(NativeUi ui,LinearLayout chart,List<Sample> samples){chart.removeAllViews();if(samples==null||samples.isEmpty())return;BigDecimal min=samples.get(0).value,max=min,sum=BigDecimal.ZERO;for(Sample sample:samples){min=min.min(sample.value);max=max.max(sample.value);sum=sum.add(sample.value);}chart.addView(ui.title("数值趋势 · "+samples.size()+" 个样本",18));ui.pair(chart,"当前",samples.get(samples.size()-1).text);ui.pair(chart,"最小 / 最大",min.toString()+" / "+max.toString());ui.pair(chart,"平均（近似）",sum.divide(new BigDecimal(samples.size()),MathContext.DECIMAL64).toString());chart.addView(ui.text("柱长按当前范围归一化；布尔值为 1/0。原始数值保留完整精度",12,NativeUi.MUTED));BigDecimal range=max.subtract(min);for(int i=Math.max(0,samples.size()-16);i<samples.size();i++){Sample sample=samples.get(i);LinearLayout row=ui.row();String time=sample.time.length()>=19?sample.time.substring(11,19):sample.time;TextView label=ui.text(time+"  "+sample.text,11,NativeUi.INK);label.setMaxLines(2);label.setTextIsSelectable(true);row.addView(label,new LinearLayout.LayoutParams(ui.dp(155),-2));ProgressBar bar=new ProgressBar(ui.context,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(1000);int progress=range.signum()==0?500:sample.value.subtract(min).divide(range,MathContext.DECIMAL64).multiply(new BigDecimal(1000)).intValue();bar.setProgress(Math.max(0,Math.min(1000,progress)));bar.setContentDescription(sample.text);row.addView(bar,new LinearLayout.LayoutParams(0,ui.dp(30),1));chart.addView(row);}}
}
