package io.github.liveyum.iotools;
import android.content.ContentResolver;
import android.database.Cursor;
import android.net.Uri;
import android.provider.DocumentsContract;
import android.provider.OpenableColumns;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.zip.*;
/** Platform-only bounded file transport. All presentation belongs to Flutter. */
final class MobileFiles {
 static final long DEFAULT_LIMIT=1L<<30, MAX_LIMIT=8L<<30;
 static final int MAX_ZIP_ENTRIES=256;
    static final class Cancel {
        private final AtomicBoolean cancelled=new AtomicBoolean();
        private final Set<Closeable> streams=Collections.synchronizedSet(new HashSet<>());
        void check() throws IOException { if(cancelled.get()||Thread.currentThread().isInterrupted())throw new InterruptedIOException("文件操作已取消"); }
        void track(Closeable stream)throws IOException{check();streams.add(stream);if(cancelled.get()){streams.remove(stream);stream.close();check();}}
        void release(Closeable stream){streams.remove(stream);}
        void signal(){cancelled.set(true);}
        void cancel(){cancelled.set(true);Closeable[] all; synchronized(streams){all=streams.toArray(new Closeable[0]);}for(Closeable stream:all)try{stream.close();}catch(IOException ignored){}}
        boolean cancelled(){return cancelled.get();}
    }
    static final class DocumentInfo { final String name;final long size;DocumentInfo(String name,long size){this.name=name;this.size=size;} }
    static final class Bundle { final File directory;final List<File> files;final long bytes;Bundle(File directory,List<File> files,long bytes){this.directory=directory;this.files=files;this.bytes=bytes;} }
    static long copyBounded(InputStream input,OutputStream output,long limit,long knownSize,Cancel cancel)throws IOException{if(limit<0||limit>MAX_LIMIT)throw new IOException("流式复制上限无效");if(knownSize>limit)throw new IOException("文件超过允许大小，未写入目标");byte[] buffer=new byte[64<<10];long total=0;while(true){cancel.check();int wanted=(int)Math.min(buffer.length,limit-total+1);int n=input.read(buffer,0,wanted);if(n<0)break;if(n==0){int one=input.read();if(one<0)break;if(total==limit)throw new IOException("文件超过允许大小");cancel.check();output.write(one);total++;continue;}if(n>limit-total)throw new IOException("文件超过允许大小");cancel.check();output.write(buffer,0,n);total+=n;}cancel.check();if(knownSize>=0&&total!=knownSize)throw new IOException("文档声明的大小与实际内容不一致");return total;}
    static DocumentInfo documentInfo(ContentResolver resolver,Uri uri){String name="data.bin";long size=-1;try(Cursor cursor=resolver.query(uri,new String[]{OpenableColumns.DISPLAY_NAME,OpenableColumns.SIZE},null,null,null)){if(cursor!=null&&cursor.moveToFirst()){int n=cursor.getColumnIndex(OpenableColumns.DISPLAY_NAME),s=cursor.getColumnIndex(OpenableColumns.SIZE);if(n>=0&&!cursor.isNull(n))name=cursor.getString(n);if(s>=0&&!cursor.isNull(s))size=cursor.getLong(s);}}catch(Exception ignored){}if(name==null||name.isEmpty())name="data.bin";return new DocumentInfo(name,size<0?-1:size);}
    static File importDocument(ContentResolver resolver,Uri uri,File root,long limit,Cancel cancel)throws IOException{checkLimit(limit);DocumentInfo info=documentInfo(resolver,uri);if(info.size>limit)throw new IOException("所选文档超过允许大小，未创建附件");File target=new File(root,"attachment-"+UUID.randomUUID()+"-"+safeName(info.name));boolean complete=false;try(InputStream input=resolver.openInputStream(uri)){if(input==null)throw new IOException("无法读取所选文档");cancel.track(input);try{try(OutputStream output=Files.newOutputStream(target.toPath(),StandardOpenOption.CREATE_NEW,StandardOpenOption.WRITE)){cancel.track(output);try{copyBounded(input,output,limit,info.size,cancel);output.flush();}finally{cancel.release(output);}}cancel.check();complete=true;return target;}finally{cancel.release(input);}}finally{if(!complete)deleteOwned(target);}}
    static void exportDocument(ContentResolver resolver,Uri uri,File file,long limit,Cancel cancel)throws IOException{checkLimit(limit);if(!file.isFile()||Files.isSymbolicLink(file.toPath()))throw new IOException("导出来源必须是普通文件");long size=file.length();if(size>limit)throw new IOException("文件超过允许大小，未打开目标文档");boolean complete=false;try(InputStream input=new FileInputStream(file)){cancel.track(input);try(OutputStream output=resolver.openOutputStream(uri,"w")){if(output==null)throw new IOException("无法打开新文档");cancel.track(output);try{copyBounded(input,output,limit,size,cancel);output.flush();}finally{cancel.release(output);}}finally{cancel.release(input);}cancel.check();complete=true;}catch(Exception error){IOException failure=error instanceof IOException?(IOException)error:new IOException("文档提供程序中断导出",error);if(!deleteDocument(resolver,uri))throw new IOException(failure.getMessage()+"；文档提供程序无法删除未完成目标，请在所选位置移除该文件",failure);throw failure;}}
    static void exportTextDocument(ContentResolver resolver,Uri uri,String text,long limit,Cancel cancel)throws IOException{if(text==null)throw new IOException("没有待导出文本");boolean complete=false;try(OutputStream raw=resolver.openOutputStream(uri,"w")){if(raw==null)throw new IOException("无法打开目标文档");cancel.track(raw);try{OutputStream bounded=new FilterOutputStream(raw){long bytes;public void write(int value)throws IOException{cancel.check();if(bytes==limit)throw new IOException("文本超过导出上限");out.write(value);bytes++;}public void write(byte[] b,int offset,int count)throws IOException{cancel.check();if(count>limit-bytes)throw new IOException("文本超过导出上限");out.write(b,offset,count);bytes+=count;}};Writer writer=new OutputStreamWriter(bounded,StandardCharsets.UTF_8);for(int offset=0;offset<text.length();offset+=8192){cancel.check();writer.write(text,offset,Math.min(8192,text.length()-offset));}writer.close();cancel.check();complete=true;}finally{cancel.release(raw);}}catch(Exception error){IOException failure=error instanceof IOException?(IOException)error:new IOException("文档提供程序中断导出",error);if(!deleteDocument(resolver,uri))throw new IOException(failure.getMessage()+"；未完成文档无法自动删除，请在所选位置移除",failure);throw failure;}}
    static boolean deleteDocument(ContentResolver resolver,Uri uri){try{return DocumentsContract.deleteDocument(resolver,uri);}catch(Exception ignored){return false;}}
    static void checkLimit(long limit)throws IOException{if(limit<1||limit>MAX_LIMIT)throw new IOException("大小上限必须为 1 字节至 8 GiB");}
    static String safeName(String name){String cleaned=name.replaceAll("[/\\\\\\p{Cntrl}]","_");if(cleaned.equals(".")||cleaned.equals("..")||cleaned.isEmpty())cleaned="data.bin";if(cleaned.length()>96)cleaned=cleaned.substring(cleaned.length()-96);if(!cleaned.isEmpty()&&Character.isLowSurrogate(cleaned.charAt(0)))cleaned=cleaned.substring(1);while(cleaned.getBytes(StandardCharsets.UTF_8).length>120)cleaned=cleaned.substring(Character.charCount(cleaned.codePointAt(0)));return cleaned;}
    static File privateFile(File root,File candidate,boolean existing)throws IOException{File base=root.getCanonicalFile(),path=candidate.isAbsolute()?candidate:new File(base,candidate.getPath());String prefix=base.getPath()+File.separator;File canonical=path.getCanonicalFile();if(!canonical.getPath().startsWith(prefix))throw new IOException("路径不在应用私有目录内");File cursor=path.getAbsoluteFile();while(cursor!=null&&!cursor.equals(base)){if(Files.isSymbolicLink(cursor.toPath()))throw new IOException("不支持符号链接文件");cursor=cursor.getParentFile();}if(existing&&!canonical.isFile())throw new IOException("请选择已存在的普通文件");return canonical;}
    static String safeZipPath(String raw)throws IOException{if(raw==null||raw.length()==0||raw.length()>1024||raw.startsWith("/")||raw.startsWith("\\")||raw.contains("\\")||raw.indexOf(':')>=0||raw.matches(".*[\\p{Cntrl}].*"))throw new IOException("ZIP 包含绝对、URI 或无效路径");String name=raw.endsWith("/")?raw.substring(0,raw.length()-1):raw;String[] parts=name.split("/",-1);if(parts.length>32)throw new IOException("ZIP 目录层级超过 32");for(String part:parts)if(part.isEmpty()||part.equals(".")||part.equals(".."))throw new IOException("ZIP 包含目录穿越或空路径");return name;}
    static Bundle extractBundle(InputStream input,File root,long limit,long knownCompressed,Cancel cancel)throws IOException{checkLimit(limit);if(knownCompressed>limit)throw new IOException("ZIP 文件超过允许大小");File base=root.getCanonicalFile(),stage=new File(base,"bundle-"+UUID.randomUUID());if(!stage.mkdir())throw new IOException("无法创建新的私有文件包目录");List<File> files=new ArrayList<>();Set<String> names=new HashSet<>();long expanded=0;boolean complete=false;
        InputStream bounded=new FilterInputStream(input){long bytes;public int read()throws IOException{byte[] one=new byte[1];int n=read(one,0,1);return n<0?-1:one[0]&255;}public int read(byte[] b,int offset,int count)throws IOException{cancel.check();int n=super.read(b,offset,(int)Math.min(count,limit-bytes+1));if(n>limit-bytes)throw new IOException("ZIP 压缩文件超过上限");if(n>0)bytes+=n;return n;}};
        try(ZipInputStream zip=new ZipInputStream(bounded,StandardCharsets.UTF_8)){int entries=0;ZipEntry entry;while((entry=zip.getNextEntry())!=null){cancel.check();if(++entries>MAX_ZIP_ENTRIES)throw new IOException("ZIP 最多包含 "+MAX_ZIP_ENTRIES+" 个项目");String name=safeZipPath(entry.getName());if(!names.add(name))throw new IOException("ZIP 包含重复路径："+name);File target=new File(stage,name);privateFile(stage,target,false);if(entry.isDirectory()){Files.createDirectories(target.toPath());}else{if(entry.getSize()>limit-expanded)throw new IOException("ZIP 解压总大小超过上限");File parent=target.getParentFile();Files.createDirectories(parent.toPath());long left=limit-expanded;try(OutputStream output=Files.newOutputStream(target.toPath(),StandardOpenOption.CREATE_NEW,StandardOpenOption.WRITE)){long count=copyBounded(zip,output,left,entry.getSize(),cancel);if(count>left)throw new IOException("ZIP 解压总大小超过上限");expanded+=count;}files.add(target);}zip.closeEntry();}if(files.isEmpty())throw new IOException("ZIP 没有可导入文件");cancel.check();complete=true;return new Bundle(stage,files,expanded);}catch(IllegalArgumentException malformed){throw new IOException("ZIP 编码或结构无效",malformed);}finally{if(!complete)deleteOwned(stage);}}
    static void deleteOwned(File path){if(path==null)return;if(Files.isSymbolicLink(path.toPath())){path.delete();return;}File[] children=path.isDirectory()?path.listFiles():null;if(children!=null)for(File child:children)deleteOwned(child);path.delete();}
}
