//go:build android || ios || sqlite_android_test

package engine

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"net/url"
	"strconv"
	"strings"

	"github.com/mattn/go-sqlite3"
)

// Android must reach the OS through the NDK/Bionic C library. The pure-Go libc
// implementation issues legacy Linux syscalls that Android's seccomp rejects.
// iOS also uses its supported native C ABI and the same bundled SQLite source.
// sqlite_android_test selects this same bundled-C driver on a CGO-enabled host.
// Do not build with libsqlite3: the application bundles SQLite, not a device ABI.
func init() {
	sql.Register("sqlite", &sqliteBionicDriver{})
}

type sqliteBionicDriver struct {
	driver sqlite3.SQLiteDriver
}

func (d *sqliteBionicDriver) Open(name string) (driver.Conn, error) {
	dsn, err := sqliteBionicDSN(name)
	if err != nil {
		return nil, err
	}
	conn, err := d.driver.Open(dsn)
	if err != nil {
		return nil, err
	}
	native, ok := conn.(*sqlite3.SQLiteConn)
	if !ok {
		conn.Close()
		return nil, fmt.Errorf("unexpected bundled SQLite connection type")
	}
	return &sqliteBionicConn{SQLiteConn: native}, nil
}

// Embedding forwards the driver's context-aware query/exec/transaction methods,
// including cancellation, while retaining the history snapshot API used by the
// existing transactional SQL preview/backup/migration implementation.
type sqliteBionicConn struct {
	*sqlite3.SQLiteConn
}

func (c *sqliteBionicConn) Serialize() ([]byte, error) {
	return c.SQLiteConn.Serialize("main")
}

// sqliteBionicDSN translates only the modernc pragmas generated by history code.
// URI filenames are not decoded/re-encoded: escaped %, ?, #, Unicode and spaces
// must designate the same existing file. SQLite mode=ro/rw remains native and is
// never replaced by the query_only flag (the two protections are independent).
func sqliteBionicDSN(name string) (string, error) {
	base, query, _ := strings.Cut(name, "?")
	params, err := url.ParseQuery(query)
	if err != nil {
		return "", fmt.Errorf("invalid SQLite URI options: %w", err)
	}
	for key, values := range params {
		if strings.HasPrefix(key, "_") && key != "_pragma" {
			return "", fmt.Errorf("unsupported SQLite driver option %q", key)
		}
		if key != "_pragma" && len(values) != 1 {
			return "", fmt.Errorf("duplicate SQLite URI option %q", key)
		}
	}
	pragmas := params["_pragma"]
	params.Del("_pragma")
	// Match SQLite/modernc defaults. mattn otherwise sets synchronous=NORMAL and
	// a five-second busy timeout even when the URI did not request either one.
	params.Set("_synchronous", "FULL")
	params.Set("_busy_timeout", "0")
	seen := map[string]bool{}
	for _, pragma := range pragmas {
		pragma = strings.TrimSpace(pragma)
		key, value, found := strings.Cut(pragma, "(")
		key = strings.ToLower(strings.TrimSpace(key))
		if !found || !strings.HasSuffix(value, ")") {
			return "", fmt.Errorf("unsupported SQLite pragma %q", pragma)
		}
		value = strings.TrimSpace(strings.TrimSuffix(value, ")"))
		if seen[key] {
			return "", fmt.Errorf("duplicate SQLite pragma %q", key)
		}
		seen[key] = true
		n, err := strconv.ParseUint(value, 10, 31)
		if err != nil {
			return "", fmt.Errorf("invalid SQLite pragma value for %q", key)
		}
		switch key {
		case "busy_timeout":
			params.Set("_busy_timeout", strconv.FormatUint(n, 10))
		case "foreign_keys", "query_only":
			if n > 1 {
				return "", fmt.Errorf("SQLite pragma %q requires 0 or 1", key)
			}
			params.Set("_"+key, strconv.FormatUint(n, 10))
		default:
			return "", fmt.Errorf("unsupported SQLite pragma %q", key)
		}
	}
	return base + "?" + params.Encode(), nil
}
