#!/usr/bin/env python3
"""Device dependency isolation, production closure and source-restore regression."""
import copy
import importlib.util
import json
from pathlib import Path
import tempfile
import unittest
from unittest.mock import patch

spec = importlib.util.spec_from_file_location("device_release", Path(__file__).with_name("prepare-ios-device-release.py"))
release = importlib.util.module_from_spec(spec)
spec.loader.exec_module(release)

MANIFEST = (b"name: app\ndependencies:\n  prod: ^1.0.0\n"
            b"dev_dependencies:\n  flutter_test:\n    sdk: flutter\n"
            b"  integration_test:\n    sdk: flutter\nflutter:\n  assets:\n    - lib/asset.txt\n")
GRAPH = {"root": "app", "packages": [
    {"name": "app", "version": "1.0.0", "kind": "root", "source": "root",
     "directDependencies": ["prod"], "devDependencies": ["integration_test"]},
    {"name": "prod", "version": "1.0.0", "source": "hosted", "directDependencies": ["nested"]},
    {"name": "nested", "version": "2.0.0", "source": "hosted", "directDependencies": []},
    {"name": "integration_test", "version": "0.0.0", "source": "sdk", "directDependencies": []}]}


def lockfile(graph):
    return ("# Generated by pub\npackages:\n" + "".join(
        f'  {row["name"]}:\n    dependency: transitive\n    source: {row["source"]}\n    version: "{row["version"]}"\n'
        for row in graph["packages"] if row["name"] != "app") + 'sdks:\n  dart: ">=3.9.0"\n').encode()


def staged_graph():
    graph = copy.deepcopy(GRAPH)
    graph["packages"] = [row for row in graph["packages"] if row["name"] != "integration_test"]
    graph["packages"][0]["devDependencies"] = []
    return graph


class DeviceReleaseTests(unittest.TestCase):
    def test_removes_exactly_one_sdk_dev_stanza_and_preserves_all_other_bytes(self):
        self.assertEqual(release.device_manifest(MANIFEST), MANIFEST.replace(release.REMOVED, b""))
        for invalid in (MANIFEST.replace(b"dev_dependencies:", b"other:"),
                        MANIFEST.replace(b"integration_test:\n    sdk: flutter", b"integration_test: ^1.0.0"),
                        MANIFEST + release.REMOVED, MANIFEST.replace(release.REMOVED, b"")):
            with self.assertRaises(RuntimeError):
                release.device_manifest(invalid)

    def test_transitive_production_graph_and_original_lock_are_required(self):
        staged = staged_graph()
        self.assertEqual(set(release.verify_production(GRAPH, staged, lockfile(GRAPH), lockfile(staged))), {"prod", "nested"})
        for changed_field, value in (("version", "2.1.0"), ("source", "git"), ("directDependencies", ["new"])):
            changed = copy.deepcopy(staged)
            changed["packages"][2][changed_field] = value
            if changed_field == "directDependencies":
                changed["packages"].append({"name": "new", "version": "1", "source": "hosted", "directDependencies": []})
            with self.assertRaisesRegex(RuntimeError, "Production dependency"):
                release.verify_production(GRAPH, changed, lockfile(GRAPH), lockfile(changed))
        with self.assertRaisesRegex(RuntimeError, "lock entry"):
            release.verify_production(GRAPH, staged, lockfile(GRAPH), lockfile(staged).replace(b'"2.0.0"', b'"2.1.0"'))
        with self.assertRaisesRegex(RuntimeError, "Original graph"):
            bad_lock = lockfile(GRAPH).replace(b'"2.0.0"', b'"2.1.0"')
            release.verify_production(GRAPH, staged, bad_lock, bad_lock)

    def test_production_test_dependency_and_unresolved_test_plugin_are_rejected(self):
        production = copy.deepcopy(GRAPH)
        production["packages"][1]["directDependencies"].append("integration_test")
        with self.assertRaisesRegex(RuntimeError, "production dependency"):
            release.production_closure(production)
        with self.assertRaisesRegex(RuntimeError, "remains resolved"):
            release.verify_production(GRAPH, GRAPH, lockfile(GRAPH), lockfile(GRAPH))

    def fixture(self, root):
        mobile = root / "mobile"
        for folder in (mobile / ".dart_tool", mobile / "ios/Runner", mobile / "lib"):
            folder.mkdir(parents=True, exist_ok=True)
        (mobile / "pubspec.yaml").write_bytes(MANIFEST)
        (mobile / "pubspec.lock").write_bytes(lockfile(GRAPH))
        (mobile / "lib/asset.txt").write_bytes(b"unchanged asset")
        self.metadata(mobile, include_test=True)
        return mobile

    def metadata(self, mobile, include_test=False, missing_plugin=False):
        names = list(release.REQUIRED_PLUGINS)
        if missing_plugin:
            names.pop()
        if include_test:
            names.append("integration_test")
        metadata = {"plugins": {"ios": [{"name": name, "dev_dependency": name == "integration_test"} for name in names]}}
        (mobile / ".flutter-plugins-dependencies").write_text(json.dumps(metadata))
        (mobile / ".dart_tool/package_config.json").write_text(json.dumps({"packages": [{"name": name} for name in names]}))
        text = "\n".join(f"// {name}\n[{release.REQUIRED_PLUGINS.get(name, 'IntegrationTestPlugin')} registerWithRegistrar:registry];" for name in names)
        (mobile / "ios/Runner/GeneratedPluginRegistrant.m").write_text(text)

    def exercise_wrapper(self, failure=None):
        with tempfile.TemporaryDirectory() as folder:
            root = Path(folder)
            mobile = self.fixture(root)
            calls = []
            def run(args, target, evidence, name, timeout):
                self.assertEqual(target, mobile)
                self.assertEqual(args[0], "flutter")
                calls.append(args)
                if name == "original-deps":
                    return json.dumps(GRAPH)
                if name == "pub-get":
                    self.assertEqual(args, ["flutter", "pub", "get", "--offline"])
                    self.assertEqual((mobile / "pubspec.yaml").read_bytes(), MANIFEST.replace(release.REMOVED, b""))
                    (mobile / "pubspec.lock").write_bytes(lockfile(staged_graph()))
                    if failure == "pub":
                        raise RuntimeError("pub failed")
                    self.metadata(mobile, missing_plugin=failure == "plugin")
                    return ""
                if name == "staged-deps":
                    graph = staged_graph()
                    if failure == "transitive":
                        graph["packages"][2]["version"] = "2.1.0"
                    return json.dumps(graph)
                self.assertEqual(name, "build")
                self.assertEqual(args, ["flutter", "build", "ios", "--release", "--no-codesign", "--no-pub", "--dart-define=IOTOOLS_SHA=test-sha"])
                if failure == "build":
                    raise RuntimeError("build failed")
                if failure == "asset":
                    (mobile / "lib/asset.txt").write_bytes(b"unexpected change")
                return ""
            with patch.object(release, "run_command", side_effect=run):
                if failure:
                    with self.assertRaises(RuntimeError):
                        release.build_device_release(root, "test-sha")
                else:
                    release.build_device_release(root, "test-sha")
            self.assertEqual((mobile / "pubspec.yaml").read_bytes(), MANIFEST)
            self.assertEqual((mobile / "pubspec.lock").read_bytes(), lockfile(GRAPH))
            report = json.loads((root / "platform-evidence/ios/device-release-dependencies.json").read_text())
            self.assertTrue(report["manifests_restored"])
            self.assertEqual(report["status"], "failed" if failure else "device_release_built_with_isolated_test_dependency")
            if failure in ("pub", "plugin", "transitive"):
                self.assertFalse(any("build" in call for call in calls))
            if not failure:
                self.assertNotIn("IntegrationTest", (root / "platform-evidence/ios/device-release-GeneratedPluginRegistrant.m").read_text())
                self.assertNotIn("integration_test", (mobile / ".flutter-plugins-dependencies").read_text())
                self.assertEqual(report["required_plugins"], sorted(release.REQUIRED_PLUGINS))

    def test_success_restores_manifests_and_keeps_staged_metadata(self):
        self.exercise_wrapper()

    def test_pub_failure_restores_both_manifests(self):
        self.exercise_wrapper("pub")

    def test_required_plugin_loss_prevents_build_and_restores_manifests(self):
        self.exercise_wrapper("plugin")

    def test_transitive_version_drift_prevents_build_and_restores_manifests(self):
        self.exercise_wrapper("transitive")

    def test_build_failure_restores_both_manifests(self):
        self.exercise_wrapper("build")

    def test_asset_mutation_fails_and_restores_manifests(self):
        self.exercise_wrapper("asset")

    def test_evidence_write_failure_still_restores_both_manifests(self):
        with tempfile.TemporaryDirectory() as folder:
            root = Path(folder)
            mobile = self.fixture(root)
            original_write = Path.write_bytes
            def write(path, data):
                if path.name == "device-release-staged-pubspec.yaml":
                    raise OSError("evidence disk failure")
                return original_write(path, data)
            with patch.object(release, "run_command", side_effect=[json.dumps(GRAPH), RuntimeError("pub failed")]), \
                 patch.object(Path, "write_bytes", write):
                with self.assertRaisesRegex(OSError, "evidence disk failure"):
                    release.build_device_release(root, "test-sha")
            self.assertEqual((mobile / "pubspec.yaml").read_bytes(), MANIFEST)
            self.assertEqual((mobile / "pubspec.lock").read_bytes(), lockfile(GRAPH))


if __name__ == "__main__":
    unittest.main()
