package mobileapi

var actionLabels = map[string]string{
	"GET": "获取资源", "HEAD": "读取响应头", "OPTIONS": "查询允许的方法", "POST": "提交数据", "PUT": "替换资源", "PATCH": "修改资源", "DELETE": "删除资源", "TRACE": "诊断回显", "CONNECT": "建立隧道",
	"subscribe": "订阅实时数据", "read-one": "读取一条消息", "publish": "发布消息", "preview-retained": "预览保留消息", "clean-retained": "清理保留消息",
	"topics": "浏览主题", "brokers": "浏览代理节点", "groups": "浏览消费组", "group": "查看消费组", "lag": "查看消费延迟", "offsets": "读取分区偏移量", "topic-config": "查看主题配置", "consume": "消费记录", "produce": "生产记录", "create-topic": "创建主题", "delete-topic": "删除主题", "alter-topic": "修改主题配置", "expand-partitions": "扩展主题分区", "delete-group": "删除消费组", "schemas": "浏览模式主题", "schema": "查看模式", "schema-versions": "查看模式版本", "register-schema": "注册模式", "delete-subject": "软删除模式主题", "purge-subject": "永久删除模式主题", "delete-schema": "删除模式版本", "connectors": "浏览连接器", "connector": "查看连接器", "update-connector": "更新连接器", "pause-connector": "暂停连接器", "resume-connector": "恢复连接器", "delete-connector": "删除连接器",
	"read-holding": "读取保持寄存器", "read-input": "读取输入寄存器", "read-coils": "读取线圈", "read-discrete": "读取离散输入", "write-register": "写入单个寄存器", "write-registers": "写入多个寄存器", "write-coil": "写入单个线圈", "write-coils": "写入多个线圈", "write-typed": "写入类型化数值", "read-write-registers": "同时读写寄存器 FC23", "read-device-id": "读取设备标识", "scan-units": "扫描指定单元", "sweep-holding": "连续扫描保持寄存器", "sweep-input": "连续扫描输入寄存器", "sweep-coils": "连续扫描线圈", "sweep-discrete": "连续扫描离散输入", "search-holding": "搜索寄存器数值", "read-raw": "读取原始 PDU", "write-raw": "写入原始 PDU",
	"discover": "发现服务器端点", "browse": "浏览子节点", "references": "浏览节点引用", "attributes": "读取全部属性", "read": "读取节点值", "write": "写入节点值", "call": "调用节点方法", "browse-path": "解析浏览路径", "node-path": "生成节点路径", "method-arguments": "读取方法签名",
}
var fieldLabels = map[string]string{
	"headers": "请求头", "query": "查询参数", "body": "原始正文", "json": "JSON 正文", "form_urlencoded": "表单字段", "form_multipart": "多段表单", "body_file": "上传文件", "body_stream": "流式正文模板", "response_file": "下载输出文件", "max_upload_bytes": "上传字节上限", "max_response_bytes": "响应字节上限", "query_filter": "响应查询过滤器", "bearer": "Bearer 令牌", "username": "用户名", "password": "密码", "ca_file": "CA 证书文件", "cert_file": "客户端证书文件", "key_file": "客户端私钥文件", "follow_redirects": "跟随重定向", "max_redirects": "重定向次数上限", "redirect_origins": "允许重定向的来源", "ignore_certificate_hosts": "证书验证例外主机", "persist": "保存 HTTP 历史", "crypto": "加密算法定义", "request_crypto": "请求加密器", "request_transforms": "请求转换步骤", "response_transform": "响应转换步骤",
	"topic": "主题", "topics": "多个主题过滤器", "qos": "服务质量 QoS", "payload": "消息载荷", "payload_encoding": "载荷编码", "retain": "保留消息", "client_id": "客户端标识", "limit": "记录数量上限", "ignore_retained": "忽略保留消息", "auto_reconnect": "自动重连读取", "reconnect_interval_ms": "重连间隔（毫秒）", "scan_duration_ms": "扫描时长（毫秒）", "max_topics": "主题数量上限", "confirm_topics": "已确认的确切主题", "confirm_token": "保留消息预览令牌",
	"group": "消费组", "groups": "多个消费组", "partition": "分区编号", "consume_partitions": "读取指定分区", "offset": "起始偏移量", "start_time": "起始时间", "filter": "记录过滤器", "key_filter": "消息键过滤器", "key_prefix": "消息键前缀", "value_prefix": "消息值前缀", "key": "消息键", "value": "数值或消息值", "partitions": "分区总数", "replication_factor": "副本数量", "configs": "主题配置项", "tls": "启用 TLS", "sasl": "SASL 认证方式", "subject": "模式主题", "version": "模式版本", "confirm_subject": "确认删除的模式主题", "connector": "连接器名称", "key_format": "消息键格式", "value_format": "消息值格式", "key_subject": "消息键模式主题", "value_subject": "消息值模式主题", "key_version": "消息键模式版本", "value_version": "消息值模式版本", "schema_registry_url": "模式注册服务地址", "schema_registry_username": "模式注册服务用户名", "schema_registry_password": "模式注册服务密码", "schema_registry_bearer": "模式注册服务令牌", "schema_registry_ca_file": "模式注册服务 CA", "schema_registry_cert_file": "模式注册服务证书", "schema_registry_key_file": "模式注册服务私钥",
	"unit": "设备单元 ID", "address": "起始地址", "count": "读取数量", "values": "多个写入值", "value_type": "数值类型", "word_order": "字节与字顺序", "samples": "采样次数", "interval_ms": "采样间隔（毫秒）", "read_address": "FC23 读取起始地址", "read_count": "FC23 读取数量", "units": "扫描的单元 ID 列表", "end_address": "结束地址", "match_value": "搜索目标值", "pdu_hex": "原始 PDU 十六进制", "read_code": "设备标识读取代码", "object_id": "对象标识", "scan_type": "扫描寄存器空间", "sweep_cycles": "扫描轮数", "sweep_recover": "读取失败后继续扫描", "stop_first": "找到首个结果后停止", "connect_timeout_ms": "连接超时（毫秒）", "request_timeout_ms": "单次请求超时（毫秒）", "request_gap_ms": "请求间隔（毫秒）", "baud": "串口波特率", "data_bits": "串口数据位", "parity": "串口校验位", "stop_bits": "串口停止位", "pins": "固定寄存器", "labels": "寄存器标签", "rules": "寄存器解释规则", "columns": "显示列", "keymap": "桌面快捷键兼容配置", "matrix_columns": "矩阵列数", "write_log_file": "写入审计日志文件", "write_log_previous": "写入前的已知数值", "next_config": "下一个配置文件",
	"node_id": "节点标识", "node_ids": "多个节点标识", "browse_path": "浏览路径", "method_id": "方法标识", "arguments": "方法调用参数", "attribute": "属性编号", "attributes": "多个属性", "direction": "引用方向", "reference_type": "引用类型", "include_subtypes": "包含引用子类型", "max_references": "引用数量上限", "max_events": "订阅事件数量上限", "security_policy": "安全策略", "security_mode": "消息安全模式", "server_cert_sha256": "服务器证书 SHA-256", "allow_insecure": "明确允许无加密连接", "allow_legacy_security": "明确允许旧安全策略", "auth": "身份认证方式", "auth_cert_file": "身份认证证书", "auth_key_file": "身份认证私钥",
}
